### ISSUE TITLE
Localization of aside.md into Indonesian

### ISSUE THREAD

**Issue by harlyumboh** [mozilla/mozilla-club-activity-kraken-the-code#10]
#### Audience
- 8+
- Pemikir kritis Pemula
- Semua orang pada MLN
#### Bahan
- Ketas dan Pena
- Web browser
- Cetakan [Lembar Kerja Legit-o-Meter](https://docs.google.com/a/zythepsary.com/file/d/0B1vyNnSVEMIDbDVLX1E4ZXRmclE/edit)
#### Tujuan Pembelajaran
- Mencari informasi yang relevan dengan menggunakan mesin pencari
- Membandingkan dan memilah informasi yang ditemukan menggunakan beberapa pencarian
- Membandingkan informasi dari sejumlah sumber untuk menilai keabsahan mereka
- Memutuskan informasi yang terpercaya dengan mengidentifikasi indikator kunci
- Dokumen kepengarangan sebuah situs web dan konten mereka
#### Bagaimana peserta didik menjadi mentor
- Seorang mahasiswa atau fasilitator yang kurang berpengalaman sehingga mereka dapat berlatih terlebih dahulu pada kegiatan ini.
- Jika beberapa siswa belajar lebih cepat atau lebih percaya diri dalam kegiatan ini, meminta mereka untuk melihat mentor kelompok lain.
- Akhiri dengan mendorong siswa untuk mengajarkan kegiatan ini kepada teman dan keluarga mereka.
#### Lihat remix masyarakat

Periksa cara pendidik dan aktivis lain yang telah dimodifikasi kegiatan ini untuk peserta mereka yang lebih spesifik di [Forum Diskusi] kami(http://discourse.webmaker.org/t/testing-1-reading-for-the-web/1149/22).

**Comment by soapdog** [comment]
Awesome work, thanks a lot for your help :smile_cat: This L10N is now available at http://mozilla.github.io/mozilla-club-activity-kraken-the-code/#id
