### ISSUE TITLE
Localization of aside.md into Filipino

### ISSUE THREAD

**Issue by ryanermita** [mozilla/mozilla-club-activity-kraken-the-code#11]
#### Mga gagamit
- 8+
- para sa mga kabataang may mapanuring pag iisip
- Lahat sa MLN
#### Materyales
- Mga papel at panulat
- Web browser
- naka-print na [Legit-o-Meter worksheet](https://docs.google.com/a/zythepsary.com/file/d/0B1vyNnSVEMIDbDVLX1E4ZXRmclE/edit)
#### Mga Layuning Matutunan
- Humanap ng mga impormasyong may kaugnayan sa paksa sa pamamagitan ng search engines
- Pag-kumparahin ang mga makukuhang impormasyon sa paulit-ulit na paghahanap.
- Pag-kumparahin ang mga impormasyon mula sa ibata-ibang pinagmulan upang malaman kung ito ay mapagkakatiwalaan
- Malaman kung mapagkakatiwalaan ang impormasyon sa pamamagitan ng pagsusuri sa mahahalagang palatandaan
- Pag-dokumento ng pagmamay ari ng isang website at ang mga nilalaman nito
#### Paraan upang maging tagapagturo ang mag-aaral
- Gabayan ang mag-aaral o ang baguhang tagapagturo upang makasanayan nilang pangunahan ang ganitong aktibidad.
- Kung ang isang mag-aaral ay mabilis matuto, kausapin ito upang turuan ang ibang groupo.
- Sa pagtatapos ng aktibidad, anyayahan ang mga mag-aaral na ituro ito sa kanilang mga kaibigan at pamilya.
#### Tignan ang gawa ng ibang kumunidad

Tignan ang ibat-ibang paraan kung paano binago ng mga tagapagturo ang aktibidad na ito depende sa mga gagamit sa ating [Discussion Forum](http://discourse.webmaker.org/t/testing-1-reading-for-the-web/1149/22).

**Comment by soapdog** [comment]
Thanks a lot for the translation, your help is invaluable to spreading Web Literacy around the world! :smile_cat: Its now live at http://mozilla.github.io/mozilla-club-activity-kraken-the-code/#fil
