### ISSUE TITLE
Localization of activity.md into Filipino

### ISSUE THREAD

**Issue by ryanermita** [mozilla/mozilla-club-activity-kraken-the-code#12]
---

title: Kraken the Code
github: mozilla/mozilla-club-activity-kraken-the-code
github_label: View on Github
discourse_label: Discussion
image: square-kraken.png
competencies_label: Web Literacy Competencies
competencies:
    - {label: "Search", type: "search"}
### Kraken the Code

Made by [MOUSE](http://mouse.org/) and remixed for Clubs by [Mozilla](https://webmaker.org/mentor).

Gagamit ang mga mag-aaral ng Internet upang masolusyonan ang misteryo ng Kraken, ang ma-alamat na nilalang sa karagatan, at kasabay nito ay **matutunan nila ang tungkol sa search terms, keywords, at kung papaano susuriin ang katamaan at kaugnayan sa paksa ng mga impormasyon mula sa web.**

45 minuto hangang isang oras
### Paghahanda

**Sagutan ang** [Palatanungan bago ang aktibidad](http://goo.gl/forms/Uua6yKIy5E).

Sunod **gawin ang aktibidad sa sarili** upang maging pamilyar dito.

**I-print ang** [Legit-O-Meter Worksheets](https://docs.google.com/a/zythepsary.com/file/d/0B1vyNnSVEMIDbDVLX1E4ZXRmclE/edit).

**Sulatan ang tatlong papel** ng _“Totoo,” “Kathang-isip” at “Nasa pagitan ng dalawa,”_ at isabit ito sa ibat-ibang kanto ng kwarto.

---

10<br>minuto
### Panimula

Magkaroon ng **maiksing usapan kasama ang inyong mga mag-aaral tungkol sa web sources.**

> - Lahat ba ng nababasa at napapanood online ay may katotohahan?
> - Pano malalaman kung ang impormasyon sa Internet ay mapagkakatiwalaan?
> - Pano mo masasabi na ito ay di mapagkakatiwalaan?

**Pagkatapos ay suriin ang [Legit-O-Meter Worksheets](https://docs.google.com/a/zythepsary.com/file/d/0B1vyNnSVEMIDbDVLX1E4ZXRmclE/edit)** at pag-usapan ang ilan sa karaniwang patakaran kung paano malalaman ang kredibilidad ng isang website.

---

25<br>minuto
### Kraken the Code: Ang paghahanap

Hatiin ang mga mag-aaral sa **2 o 3 groupo** at ipaliwang  na ang hamon sa bawat groupo ay **patunayan kung ang maalamat na halimaw, ang Kraken, ay totoo o kathang-isip lamang.**

Magsisimula ang mga group sa **pag-gugol ng 20 minuto sa pananaliksik.** Gamit ang mga gabay mula sa [Tip Sheet](legit-o-meter.html), ang mga groupo ay **kailangan masuri ang 2 internet sources**, i-dokumento ang kanilang mga napag-alaman sa Legit-o-Meter (sa pamamagitan ng [pagsusulat sa hand-awt](https://docs.google.com/a/zythepsary.com/file/d/0B1vyNnSVEMIDbDVLX1E4ZXRmclE/edit) o pag-edit sa [online template](https://laura.makes.org/thimble/Mjg1NjA2NDAw/kraken-the-code-legit-o-meter)).

![Image](http://mozilla.github.io/webmaker-curriculum/images/kraken-in-progress.jpg)

**Alalayan ang mga mag-aaral sa pagnanaliksik** sa pamamagitan ng mga sumusunod:

> - Kausapin ang mga mag-aaral ng magsalita habang sila ay nasa proseso ng pananaliksik.
> - Magsaliksik kasama ang groupo at tanungin sila kung ano ang sunod na dapat nilang gagawin
> - Pag-parisin ang mga mag-aaral at kausapin sila na gumawa ng screencast na nagpapaliwanag ng kanilang mga desisyon.

![Mouse](http://mozilla.github.io/webmaker-curriculum/images/kraken-finished-example.jpg)

---

10<br>minuto
### Kraken the Code: Depensa

At sa pagwawakas ng pananaliksik ng mga mag-aaral, **ang mga groupo ay tatayo sa isa sa mga karatula:** "Totoo", "Kathang-isip", o "Nasa pagitan ng dalawa".

Tanungin ang bawat groupo kung ano ang kanilang mga napag-alaman tungkol sa Kraken at **depensan ang kanilang mga opinyon** sa pamamagitan ng Legit-o-Meter worksheet na kanilang napunan. Ang mga kalahok ay **maaring lumipat ng posisyon** kung sila ay nakarinig ng mga nakaka-kumbinsing argumento.

Tapusin ang aktibidad sa pag hiling sa mga groupo na pagnilayan nila ang kanilang mga nalaman.

Sagutan ang **[Palatanungan pagkatapos ng aktibidad](http://goo.gl/forms/ezm6IXWhhM)**.

**Comment by soapdog** [comment]
Thanks a lot for the translation, your help is invaluable to spreading Web Literacy around the world! :smile_cat: Its now live at http://mozilla.github.io/mozilla-club-activity-kraken-the-code/#fil

**Comment by ryanermita** [comment]
woah! cool! Thanks! 

Our team(mozilla philippines educ team) are currently working on localizing other web lit. activities. more to come :)

**Comment by ryanermita** [comment]
update some words. :)
