### ISSUE TITLE
Localization of aside.md into Hindi

### ISSUE THREAD

**Issue by join2ashish** [mozilla/mozilla-club-activity-kraken-the-code#13]
#### दर्शक
- ८+
- महत्वपूर्ण विचारकों से शुरुआत
- एम एल एन  में हर कोई
#### सामग्री
- कागजात और  कलम
- वेब ब्राउज़र
- मुद्रित  [कानूनी -ओ- मापक कार्य-पत्र]()(https://docs.google.com/a/zythepsary.com/file/d/0B1vyNnSVEMIDbDVLX1E4ZXRmclE/edit)
#### सीखने का  मकसद
- खोज इंजन का उपयोग करके प्रासंगिक जानकारी का पता लगाएँ
- आसमान वस्तुओँ की तुलना और उसके विपरीत जानकारियाँ कई खोजों के बाद पाया गया 
  *जानकारियों की तुलना कई सूत्रों से की उनकी विश्वसनीयता का न्याय करने के लिए 
  *प्रमुख संकेतकों की पहचान के द्वारा जानकारी की विश्वसनीयता पर फैसला
  *एक वेबसाइट और उनकी सामग्री के ग्रन्थकारिता दस्तावेज़
#### कैसे शिक्षार्थियाँ  संरक्षक बने

*प्रतिछाया में  छात्र या कम अनुभवी फैसिलिटेटर इस गतिविधि में प्रमुख अभ्यास कर सकते हैं ।
*अगर कुछ छात्र तेजी से बढ़ रहे या गतिविधि में अधिक विश्वास कर रहे हैं,तो उन्हें एक और समूह के संरक्षक सहकर्मी के लिए कहें।
*अपने दोस्तों और परिवार के लिए इस गतिविधि को पढ़ाने के लिए छात्रों के उत्साह से निष्कर्ष निकालना ।
#### समुदाय रीमिक्स देखें

शिक्षकों और कार्यकर्ताओं में उनके विशिष्ट दर्शकों के लिए इस गतिविधि को संशोधित किया है तरीकों की जाँच करें हमारे [विचार-विमर्श](http://discourse.webmaker.org/t/testing-1-reading-for-the-web/1149/22).

**Comment by soapdog** [comment]
Added this one to the repo! Thanks a lot for your translation, please check the issue at #14 because I've added some more comments there.
