### ISSUE TITLE
Localization of activity.md into Hindi

### ISSUE THREAD

**Issue by join2ashish** [mozilla/mozilla-club-activity-kraken-the-code#14]
---

शीर्षक : कराकेन दा कोड 
गिटहब  : मोज़िला/मोज़िला-क्लब-गतिविधि-कराकेन-दा-कोड 
गिटहब _लेबल : गिटहब पर देखें
प्रवचन_लेबल : विचार-विमर्श
प्रतिमा  : स्क्वायर -कराकेन.पी ऐन जी 
दक्षताओं_लेबल : वेब साक्षरता दक्षताओं
दक्षताओं
    -{ लेबल : "खोज",  टाइप : "खोज"}
    -{लेबल : "विश्वसनीयता", टाइप : "विश्वसनीयता"}

---
### कराकेन दा कोड

[माउस ](http://mouse.org/) द्वारा निर्मित और [ मोज़िला](https://webmaker.org/mentor) द्वारा क्लब के लिए रिमिक्स

शिक्षार्थियों कराकेन के रहस्य को सुलझाने के लिए इंटरनेट का उपयोग करेगा, एक पौराणिक समुद्र प्राणी , भी , जबकि *\* खोज शब्दों , कीवर्ड और कैसे वैधता और वेब स्रोतों की प्रासंगिकता का आकलन करने के बारे में सीखने । **

४५ मिनट से एक घंटा 
### तैयारी

[ पूर्व गतिविधि प्रश्नावली ] *_को पूरा करें *_ (http://goo.gl/forms/Uua6yKIy5E)

इसके आगे खुद से गतिविधि करें उससे परिपरिचित होने के लिए .

 [  कानूनी -ओ- मापक कार्य-पत्र ] *_को प्रिंट करें *_(https://docs.google.com/a/zythepsary.com/file/d/0B1vyNnSVEMIDbDVLX1E4ZXRmclE/edit).

"रियल" , "काल्पनिक" और " कुछ उसके अंदर " से  कागज के तीन टुकड़ो पे लेबल करें और उसको कमरें के भिन - भिन हिसों पर लगा दें 

---

१०<बी आर >मिनट 
### परिचय

*\* वेब स्रोतों के बारे में अपने शिक्षार्थियों के साथ एक संक्षिप्त बातचीत करें !  **

> - क्या जो आप ऑनलाइन पढ़ते या देखते है वो सही है ?
> - आपको कैसे पता चलता है की इंटरनेट पे जानकारियाँ सही है ?
> - आप कब बता सकते है की इंटरनेट पे जानकारियाँ साईं है ?

इसके बाद[  कानूनी -ओ- मापक कार्य-पत्र ] की समीक्षा करें (https://docs.google.com/a/zythepsary.com/file/d/0B1vyNnSVEMIDbDVLX1E4ZXRmclE/edit) एक वेबसाइट की विश्वसनीयता का निर्धारण करने के लिए कुछ सामान्य नियमों पर चर्चा करें !

---

२५ <बी आर >मिनट 
### कराकेन दा कोड :  हंट

शिक्षार्थियों को २ - ३ के  समूह में विभाजित करें और प्रत्येक समूह को चुनौती दें की साबित करें की कराकेन सही है या एक मिथ .

समूह शोध में २० मिनट खर्च करके शुरू करते हैं। [टिप शीट ] से दिशा निर्देशों का उपयोग ( कानूनी -ओ- meter.html ), समूहों *\* 2 इंटरनेट स्रोतों का मूल्यांकन करना चाहिए **, [ थिसिस पर लिखने ] द्वारा या तो ( कानूनी -ओ-मीटर पर अपने निष्कर्षों का दस्तावेजीकरण (https://docs.google.com/a/zythepsary.com/file/d/0B1vyNnSVEMIDbDVLX1E4ZXRmclE/edit) या संपादन [ ऑनलाइन टेम्पलेट ](https://laura.makes.org/thimble/Mjg1NjA2NDAw/kraken-the-code-legit-o-meter)).

![प्रतिमा](http://mozilla.github.io/webmaker-curriculum/images/kraken-in-progress.jpg)

*\* निम्नलिखित संकेतों का साथ उनके शोध के मार्गदर्शक पर विचार करें : **

> - व्यक्तिगत रूप से विश्वसनीय जानकारी के लिए खोज करने की प्रक्रिया के माध्यम से बात करने के लिए शिक्षार्थियों पूछें !
> - एक साथ एक नमूना खोज करते हैं और आगे क्या करना है समूह में पूछते हैं।
> -  शिक्षार्थियों  की जोड़ी बनाएं और अपने फैसले को स्पष्ट करने वाला स्क्रीनकास्ट बनाने के लिए उन्हें पूछें !

![माउस](http://mozilla.github.io/webmaker-curriculum/images/kraken-finished-example.jpg)

---

१०<बी आर >मिनट 
### कराकेन दा कोड :  रक्षा

शोध की अवधि के अंत में, समूहों संकेतों में से एक के तहत खड़े होंगे : "रियल , " "काल्पनिक "उसके बींच में कछ "

प्रत्येक समूह से पूछो की कराकेन  के बारे में क्या पता चला , और अपनी राय *\* रक्षा के लिए वे बाहर भरा कानूनी -ओ-मीटर कार्यपत्रकों का उपयोग करें ! वे कायल तर्कों को सुनने के यदि प्रतिभागियों *\* *\* स्थिति को बदल सकते हैं ।

 प्रतिबिंबित करने के लिए समूह से  पूछें की की उन्हें क्या मिला ! 

  [पोस्ट - गतिविधि प्रश्नावली ] को पूरा करें (http://goo.gl/forms/ezm6IXWhhM).

**Comment by soapdog** [comment]
Hey Thanks a lot for the translation :smile_cat: 

Can you please check out http://mozilla.github.io/mozilla-club-activity-kraken-the-code/#hi and see if the text is ok? I had to fix some markdown syntax on the file above and I don't know if I destroyed the text.

Thanks again for your support!

**Comment by join2ashish** [comment]
Yup!! That's fine Thank You :)

**Comment by soapdog** [comment]
Thanks a lot for the quick reply!
