### ISSUE TITLE
Localization of activity.md into German

### ISSUE THREAD

**Issue by Ryuno-Ki** [mozilla/mozilla-club-activity-kraken-the-code#15]
---

title: Kraken the Code
github: mozilla/mozilla-club-activity-kraken-the-code
github_label: View on Github
discourse_label: Discussion
image: square-kraken.png
competencies_label: Web Literacy Competencies
competencies:
    - {label: "Search", type: "search"}
### Kraken, der Code

Produziert von [MOUSE](http://mouse.org/) und remixed für Clubs von [Mozilla](https://webmaker.org/mentor).

Die Lernenden werden das Internet benutzen, um das Mysterium des Kraken zu lösen, des legendären See-Ungeheuers. Dabei **lernen sie auch etwas über Suchbegriffe, Schlüsselwörter und das Einschätzen der Vertrauenswürdigkeit und Relevanz von Quellen im Web.**

45 Minuten bis eine Stunde
### Vorbereitung

**Beantworte den** [Vorbereitungs-Fragebogen](http://goo.gl/forms/Uua6yKIy5E).

Als nächstes **absolviere die Übung selber**, um dich damit vertraut zu machen.

**Fertige einen Ausdruck** des [Legit-O-Meter Arbeitsblattes](https://docs.google.com/a/zythepsary.com/file/d/0B1vyNnSVEMIDbDVLX1E4ZXRmclE/edit) an.

**Beschrifte drei Blätter** mit  _“Real,” “Imaginär” und “Etwas dazwischen,”_ und häng sie an verschiedenen Seiten des Raumes auf.

---

10<br>min
### Einführung

**Besprech dich kurz mit den Lernenden über Quellen im Web.**

> - Ist alles, was du online liest oder siehst, wahr?
> - Wie weißt du, ob Informationen im Internet verlässlich sind?
> - Woran erkennst du, wenn das nicht der Fall ist?

**Dann geht das [Legit-O-Meter Arbeitsblatt](https://docs.google.com/a/zythepsary.com/file/d/0B1vyNnSVEMIDbDVLX1E4ZXRmclE/edit) durch**, um allgemeine Regeln zum Bestimmen der Glaubwürdigkeit einer Website zu diskutieren.

---

25<br>min
### Kraken, der Code: Jagd

Teile die Lernenden in **Gruppen von zwei bis drei Personen** ein und erläutere die Herausforderung jeder Gruppe. Diese besteht darin, zu **beweisen, ob das legendäre Monster, Der Kraken, wirklich existiert oder nur eine Sage ist.**

Die Gruppen bekommen **20 Minuten zum Recherchieren.** Anhand der Richtlinien des [Tipp-Blattes](legit-o-meter.html) sollen die Gruppen **2 Internet-Quellen auswerten** und ihre Ergebnisse im Legit-O-Meter dokumentieren. Entweder durch [das Schreiben auf dem Arbeitsblatt](https://docs.google.com/a/zythepsary.com/file/d/0B1vyNnSVEMIDbDVLX1E4ZXRmclE/edit) oder durch das Bearbeiten [der Online-Vorlage](https://laura.makes.org/thimble/Mjg1NjA2NDAw/kraken-the-code-legit-o-meter).

![Image](http://mozilla.github.io/webmaker-curriculum/images/kraken-in-progress.jpg)

**Unterstütze die Recherche** mit den folgenden Anregungen:

> - Bitte die Lernenden, jeder für sich den Prozess der Suche nach glaubwürdigen Informationen zu beschreiben.
> - Führt eine Beispiel-Suche gemeinsam durch und frage nach den nächsten Schritten.
> - Bilde Pärchen von Lernenden und bitte sie, einen Screencast anzufertigen, in dem sie ihre Entscheidungen erklären.

![Mouse](http://mozilla.github.io/webmaker-curriculum/images/kraken-finished-example.jpg)

---

10<br>min
### Kraken, der Code: Verteidigung

Am Ende der Recherche sollen **sich die Gruppen unter einem der Schilder einfinden:** “Real,” “Imaginär” oder “Etwas dazwischen”.

Frage jede Gruppe, was sie über den Kraken herausgefunden habe und bitte sie **ihre Position zu verteidigen**, wobei sie ihr ausgefülltes Legit-O-Meter-Arbeitsblatt benutzen sollen. Die Teilnehmer **können ihre Position ändern**, wenn sie von Argumenten überzeugt wurden.

Schließe die Runde mit einer Reflexion darüber, was sie gefunden haben.

Dann fülle den **[Nachbereitungs-Fragebogen aus](http://goo.gl/forms/ezm6IXWhhM)**.

**Comment by soapdog** [comment]
Thanks a lot for your support! Your translation is now live at http://mozilla.github.io/mozilla-club-activity-kraken-the-code/#de :smile_cat: 

Yaaay!!!!
