### ISSUE TITLE
Localization of aside.md into German

### ISSUE THREAD

**Issue by Ryuno-Ki** [mozilla/mozilla-club-activity-kraken-the-code#16]
#### Publikum
- 8+
- Beginner im kritischen Denken
- Jeder beim Mozilla Learning Network (MLN)
#### Material
- Papier und Stift
- Web-Browser
- Ausgedrucktes [Legit-O-Meter-Arbeitsblatt](https://docs.google.com/a/zythepsary.com/file/d/0B1vyNnSVEMIDbDVLX1E4ZXRmclE/edit)
#### Lernziele
- Relevante Informationen beim Benutzen einer Suchmaschine ausmachen
- Informationen von mehreren Suchen mit einander vergleichen und sie gegenüber stellen
- Informationen aus verschiedenen Quellen mit einander vergleichen, um auf die Glaubwürdigkeit zu schließen
- Auf die Glaubwürdigkeit einer Information schließen, indem Schlüssel-Hinweise bestimmt werden
- Den Autor einer Website und deren Inhalts dokumentieren
#### Wie Lernende zu Mentoren werden
- Begleite einen Schüler oder einen wenig erfahrenen Moderator, so dass sie das Leiten dieser Aktivität üben können.
- Falls einige Schüler schneller oder sicherer bei dieser Aktivität sind, bitte sie, eine andere Gruppe mit zu betreuen.
- Schließe mit der Aufforderung an die Schülere, ihren Freunden und Familienangehörigen diese Aktivität auch beizubringen.
#### Weitere Community Remixes

Siehe auch weitere Wege in unserem [Diskussions-Forum](http://discourse.webmaker.org/t/testing-1-reading-for-the-web/1149/22), wie Lehrende und Aktivisten diese Aktivität für ihr Publikum abgewandelt haben.

**Comment by soapdog** [comment]
Thanks a lot for your support! Your translation is now live at http://mozilla.github.io/mozilla-club-activity-kraken-the-code/#de :smile_cat: 

Yaaay!!!!
