### ISSUE TITLE
Localization of activity.md into Gujarati

### ISSUE THREAD

**Issue by moingshaikh** [mozilla/mozilla-club-activity-kraken-the-code#17]
### ક્રાકેન ધ કોડ

[માઉસ](http://mouse.org/) દ્વારા બનાવાયું અને [મોઝીલા](https://webmaker.org/mentor) દ્વારા ક્લબ માટે રિમિક્ષ કરાયું.
શીખનારાઓ ઈન્ટરનેટ નો ઉપયોગ ધ ક્રાકેન, એક સમુદ્રી પ્રાણી ના રહસ્યો ઉકેલવા માટે કરશે.

દરમ્યાન, **આ ઉપરાંત તેઓ શોધ શબ્દો, શબ્દો પણ શીખશે અને કઈ રીતે વેબ ના સ્ત્રોતો ની માન્યતા અને અનુરૂપતા ની આકારણી કરવી એ પણ શીખશે.**

45 મિનીટ થી એક કલાક સુધી.
### તૈયારી

[પૂર્વ-ગતિવિધિ પ્રશ્નોતરી](http://goo.gl/forms/Uua6yKIy5E) **ને પૂરી કરો**

**આગામી**: તમારી રીતે પ્રવૃત્તિ કરો જેથી તમે એનાથી વધુ સારી રીતે પરિચિત થાઓ 

[વાંચન જરૂરી કાર્યપત્રક](https://docs.google.com/a/zythepsary.com/file/d/0B1vyNnSVEMIDbDVLX1E4ZXRmclE/edit) ને પ્રિન્ટ કરો.

**કાગળ ના ત્રણ ટુકડા પર આ રીતના લેબલ લગાડો** _"વાસ્તિવક"_, _"કાલ્પનિક"_ અને _"આ બન્નેની વચ્ચે નું કંઈક"_ હવે આ ટુકડાઓ ને રૂમ ના અલગ અલગ હિસ્સાઓ માં લગાડી દો.
### પરિચય

10 મિનીટ 

વેબ ના સ્ત્રોતો વિષે તમારા વિદ્યાર્થીઓં સાથે સંક્ષિપ્ત માં વાર્તાલાપ કરો 
- શું તમે વેબ ઉપર જે પણ વાંચો છો અને જુઓ છો એ બધું સાચુ હોય છે?
- ઈન્ટરનેટ ઉપર ની માહિતી વિશ્વનીય છે એ તમે કઈ રીતે જાણો છો?
- ઈન્ટરનેટ ઉપર ની માહિતી વિશ્વનીય નથી  એ તમે ક્યારે કહી શકો?

આ પછી એક વેબસાઇટ ની વિશ્વસનીયતા નક્કી કરવા માટેના સામાન્ય નિયમો ચર્ચા-વિચારણા કરવા માટે [વાંચન જરૂરી કાર્યપત્રક](http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/legit-o-meter.html) ની **સમીક્ષા કરો**.
### ક્રાકેન ધ કોડ: હન્ટ

10 મિનીટ 

વિદ્યાર્થીઓ ના **2 કે 3 ના સમૂહ** ના ભાગ કરો અને તેમને સમજો કે દરેક સમૂહ નો પડકાર છે એ **સાબિત કરવાનું કે દંતકથા સમાન રાક્ષસ ધ ક્રાકેન વાસ્તવિકતા છે કે એક પૌરાણિક કથા.**

બધા સમૂહ શરૂઆત ની **20 મિનીટ રીસર્ચ કરે છે**.

[ટીપશીટ](http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/legit-o-meter.html) માંથી માર્ગદર્શન લઈને સમૂહો એ  2 ઈન્ટરનેટ સ્ત્રોતો નું મૂલ્યાંકન કરવું જોઈએ અને [વાંચન જરૂરી કાર્યપત્રક](https://docs.google.com/a/zythepsary.com/file/d/0B1vyNnSVEMIDbDVLX1E4ZXRmclE/edit) પર તેમના તારણો નું દસ્તાવેજીકરણ કરવું જોઈએ, યા તો [હેન્ડઆઉટ](https://docs.google.com/a/zythepsary.com/file/d/0B1vyNnSVEMIDbDVLX1E4ZXRmclE/edit) પર લખીને અથવા તો [ઓનલાઈન ટેમ્પ્લેટ](https://laura.makes.org/thimble/Mjg1NjA2NDAw/kraken-the-code-legit-o-meter) ને એડિટ કરીને. 

![Kraken in Progress](http://mozilla.github.io/webmaker-curriculum/images/kraken-in-progress.jpg)

 નિમ્નલિખિત મુદ્દાઓ સાથે તેમના સંશોધન ને માર્ગદર્શન આપવા પર વિચારો:
- વિશ્વસનીય માહિતી માટેની શોધ પ્રક્રિયા મારફતે વિદ્યાર્થીઓને વ્યક્તિગત વાર્તાલાપ કરવા કહો. 
- સાથે મળીને એક ઉદાહરણરૂપ / નમૂના શોધ કરો અને આગળ શું કરવું તે સમૂહ ને પૂછો.
- વિધાર્થીઓ ની જોડીઓ બનાવો અને તેમને તેમના નિર્ણયો સમજવતા સ્ક્રીનકાસ્ટ બનાવાનું કહો. 
  ![Kraken finished example](http://mozilla.github.io/webmaker-curriculum/images/kraken-finished-example.jpg)
### ક્રાકેન ધ કોડ: સંરક્ષણ

સંશોધન સમય પુરા થવા પર **સમૂહો આ પૈકી ના એક ચિન્હ નીચે ઉભા રહેશે**:

"વાસ્તિવક", "કાલ્પનિક" અને "આ બન્નેની વચ્ચે નું કંઈક".

દરેક સમૂહ ને પૂછો કે તેઓ ને ક્રકેન વિષે શું જાણ્યું અને તેમને વાંચન જરૂરી કાર્યપત્રક નો ઉપયોગ કરીને **પોતાના અભિપ્રાયો નું સંરક્ષણ** કરવા કહો.
ભાગ લેનારાઓ જો સહમતીવળ/તાર્કિક દલીલો સાંભળે તો પોતાની સ્થિતિ/જગ્યા બદલી શકે છે.

અંત માં, સમૂહો એ શું જાણ્યું એ બાબત નું પરામર્શ કરવા કહો અને તારણ કાઢો.

[ગતિવિધિ-બાદ ની પ્રશ્નાવલી](http://goo.gl/forms/ezm6IXWhhM) પૂરી કરો.

**Comment by soapdog** [comment]
Thanks a lot for this translation!!! your support is greatly appreciated. :smile_cat: 

This translation is now live at http://mozilla.github.io/mozilla-club-activity-kraken-the-code/#gu

I need some help with some missing words though. We need to translate the following words and expresions into Gujarati:
- View on Github
- Discussion
- Web Literacy Competencies
- Search
- Credibility

Can you help me? 

Thanks again!

**Comment by moingshaikh** [comment]
Hi,

I have added the above missing words' Gujarati translations in below separate comment box. Please let me know if it needs any other way.

Thanks

Moin

On Tue, Dec 1, 2015 at 2:57 AM, Andre Alves Garzia <notifications@github.com

**Comment by moingshaikh** [comment]
- View on Github - ગિટહબ પર જુઓ 
- Discussion - ચર્ચા
- Web Literacy Competencies - વેબ સાક્ષરતા સ્પર્ધાત્મકતા 
- Search - શોધ
- Credibility - વિશ્વસનીયતા
