### ISSUE TITLE
Localization of aside.md into Gujarati

### ISSUE THREAD

**Issue by moingshaikh** [mozilla/mozilla-club-activity-kraken-the-code#18]
### દર્શકગણ

૮+
જટિલ વિચારકો થી શરૂઆત 
એમેલેન માંના દરેક 
### સામગ્રી

કાગળ અને પેન 
વેબ બ્રાઉઝર
મુદ્રિત [પૂર્વ-ગતિવિધિ પ્રશ્નોતરી](http://goo.gl/forms/Uua6yKIy5E)
### શીખવાના ઉદ્દેશો
- સર્ચ-એન્જીન નો ઉપયોગ કરીને સંબંધિત માહિતી મેળવવી.
- વિવિધ સર્ચ-એન્જીન દ્વારા મેળવેલ માહિતી માં રહેલી સમાનતા અને વિરોધાભાસ ચકાસવા.
- કેટલાક સ્ત્રોતો માંથી માહિતી મેળવીને તેની વિસ્વ્સ્નીયતા ચકાસવા તુલના કરવી.
- ચાવીરૂપ સંકેતો ને ઓળખીને માહિતી ની વિસ્વસ્નીયતા નક્કી કરવી.
- એક વેબસાઈટ ના ગ્રંથકર્તા અને તેની સામગ્રી નું દસ્તાવેજીકરણ કરવું
### વિદ્યાર્થીઓ / શીખનારાઓ માર્ગદર્શક કઈ રીતે બને છે
- એક વિધાર્થી અથવા ઓછા અનુભવી ફેસીલીટેટર નું અવલોકન કરો.
- જો અમુક વિદ્યાર્થીઓ ઝડપથી આગળ વધે છે અથવા આ પ્રવૃત્તિ માં વધુ આત્મવિશ્વાસ ધરાવે છે તો તેવા વિદ્યાર્થીઓ ને અન્ય સમૂહ ને માર્ગદર્શન આપવા કહો.
- અંત માં, વિદ્યાર્થીઓ ને આ પ્રવૃત્તિ પોતાના મિત્રો અને પારિવારિક સભ્યો ને શીખવાડવા કહો.
### સામુદાયિક રીમીક્સ જુઓ

કઈ રીતે શિક્ષકો અને કાર્યકરો એ તેમના ચોક્કસ / વિશેષ દર્શકગણ માટે આ પ્રવૃત્તિ ને સંશોધિત કરી છે એ અમારા [ચર્ચા-વિચારણા ફોરમ](http://discourse.webmaker.org/t/testing-1-reading-for-the-web/1149/22) માં જુઓ.

**Comment by soapdog** [comment]
Thanks a lot for this translation!!! your support is greatly appreciated. :smile_cat: 

This translation is now live at http://mozilla.github.io/mozilla-club-activity-kraken-the-code/#gu

**Comment by moingshaikh** [comment]
Awesome! I am also working to translate other remaining chapters :+1:
