### ISSUE TITLE
Translation of aside.md into Dutch

### ISSUE THREAD

**Issue by gvanwaelvelde** [mozilla/mozilla-club-activity-kraken-the-code#19]
#### Publiek
- 8+
- beginnende kritische denkers
- Iedereen in het Mozilla Learning Network (MLN)
#### Materialen
- Pen en papier
- Webbrowser
- Afgedrukt [Legit-o-Meter werkblad](https://docs.google.com/a/zythepsary.com/file/d/0B1vyNnSVEMIDbDVLX1E4ZXRmclE/edit)
#### Leerdoelstellingen
- Gebruik zoekmachines om nuttige informatie te vinden
- Vergelijk informatie die met verschillende zoekopdrachten gevonden wordt
- Vergelijk informatie afkomstig van verschillende bronnen om hun betrouwbaarheid te beoordelen
- Bepaal de betrouwbaarheid van informatie op basis van de belangrijkste aanwijzingen
- Documenteer het auteurschap en de inhoud van een website
#### Van leerling naar mentor
- Begeleid een leerling of minder ervaren leerkracht zodat zij deze activiteit beter kunnen uitvoeren.
- Als sommige leerlingen beter zijn in het uitvoeren van een taak, vraag hen dan om mentor te worden bij een andere groep.
- Besluit met leerlingen aan te zetten om deze activiteit aan te leren aan familie en vrienden.
#### Remixes van de gemeenschap

Kijk hoe anderen deze activiteit aangepast hebben aan hun eigen doelpubliek in ons [Discussie Forum](http://discourse.webmaker.org/t/testing-1-reading-for-the-web/1149/22).

**Comment by soapdog** [comment]
Thanks a lot for the translation! :smiley_cat: 

Your awesome work is live at http://mozilla.github.io/mozilla-club-activity-kraken-the-code/#nl
