### ISSUE TITLE
activity.md translated into Dutch

### ISSUE THREAD

**Issue by gvanwaelvelde** [mozilla/mozilla-club-activity-kraken-the-code#20]
---

title: Kraken the Code
github: mozilla/mozilla-club-activity-kraken-the-code
github_label: View on Github
discourse_label: Discussion
image: square-kraken.png
competencies_label: Web Literacy Competencies
competencies:
    - {label: "Zoeken", type: "search"}
### Kraken de Code

Gemaakt door [MOUSE](http://mouse.org/) en ge-remixed voor Clubs door [Mozilla](https://webmaker.org/mentor).

Leerlingen zullen het Internet gebruiken om het mysterie van De Kraken, een legendarisch zeemonster, op te lossen, terwijl ze **leren over zoektermen, sleutelwoorden, en hoe ze betrouwbaarheid en relevantie van bronnen op het Web kunnen beoordelen.**

45 minuten tot een uur
### Voorbereiding

**Vul de** [voorbereidingsvragenlijst](http://goo.gl/forms/Uua6yKIy5E) **in**.

Doe vervolgens **de activiteit zelf** om ze te leren kennen.

**Druk de** [Legit-O-Meter Werkbladen](https://docs.google.com/a/zythepsary.com/file/d/0B1vyNnSVEMIDbDVLX1E4ZXRmclE/edit) **af**.

*_Maak drie papiertjes *_ met _“Echt,” “Verzonnen” and “Ergens daartussen,”_ en hang ze op verschillende plaatsen in de kamer.

---

10<br>min
### Inleiding

Heb een **kort gesprek met uw leerling over bronnen op het Web.**

> - Is alles dat je online leest of ziet waar?
> - Hoe weet je of informatie op het Internet betrouwbaar is?
> - Hoe zie je wanneer het niet betrouwbaar is?

**Bekijk dan het [Legit-O-Meter Werkblad](https://docs.google.com/a/zythepsary.com/file/d/0B1vyNnSVEMIDbDVLX1E4ZXRmclE/edit)** om enkele regels over de betrouwbaarheid van een website te bespreken.

---

25<br>min
### Kraken de Code: Jacht

Verdeel leerlingen in **groepjes van 2 of 3** en leg uit dat elke groep moet proberen te **bewijzen of het legendarische monster, De Kraken, echt bestaat of verzonnen is.**

Groepen beginnen met **20 minuten research.** Met de richtlijnen van het [Tipblad](legit-o-meter.html), zouden de groepen **2 internetbronnen moeten evalueren** en hun bevindingen noteren op de Legit-o-Meter ([handmatig op de gedrukte versie](https://docs.google.com/a/zythepsary.com/file/d/0B1vyNnSVEMIDbDVLX1E4ZXRmclE/edit) of door [het online sjabloon](https://laura.makes.org/thimble/Mjg1NjA2NDAw/kraken-the-code-legit-o-meter) te bewerken).

![Image](http://mozilla.github.io/webmaker-curriculum/images/kraken-in-progress.jpg)

**Ondersteun hun research** met de volgende aanmoedigingen:

> - Vraag leerlingen individueel om over het proces om betrouwbare informatie te zoeken te vertellen.
> - Doe samen een voorbeeld-zoekopdracht en vraag aan de groep hoe ze nu verder moeten.
> - Verdeel de leerlingen in groepjes van twee en vraag hen hun beslissingen uit te leggen met een screencast.

![Mouse](http://mozilla.github.io/webmaker-curriculum/images/kraken-finished-example.jpg)

---

10<br>min
### Kraken de Code: Verdediging

Aan het einde van de researchperiode **staan de groepen onder één van de bordjes:** “Echt,” “Verzonnen,” or “Ergens Daartussen”.

Vraag iedere groep wat ze over de Kraken ontdekt hebben en vraag ze om **hun meningen te verdedigen** met de Legit-o-Meter werkbladen die ze ingvuld hebben. Deelnemers **kunnen van mening veranderen** als ze overtuigende argumenten horen.

Besluit met de groep te vragen om te overlopen wat ze gevonden hebben.

Vul de **[conclusievragenlijst](http://goo.gl/forms/ezm6IXWhhM)** in.

**Comment by soapdog** [comment]
Thanks a lot for the translation! :smiley_cat: 

Your awesome work is live at http://mozilla.github.io/mozilla-club-activity-kraken-the-code/#nl
