### ISSUE TITLE
Localization of aside.md into Swedish

### ISSUE THREAD

**Issue by bobbisan** [mozilla/mozilla-club-activity-kraken-the-code#21]
#### Målgrupp
- 8+
- Begynnande källkritiker
- Alla i Mozilla Learning Networks
#### Material
- Papper och pennor
- Webbläsare (browser)
- Utskrivna [Legit-o-Meter Worksheets](https://docs.google.com/a/zythepsary.com/file/d/0B1vyNnSVEMIDbDVLX1E4ZXRmclE/edit)
#### Lärandemål
- Hitta relevant information med hjälp av sökmotorer
- Jämföra och värdera information från flera olika sökningar
- Jämföra information från många olika källor för att avgöra deras trovärdighet
- Avgöra informationens trovärdighet genom att gå igenom och identifiera vissa nyckeluppgifter
- Säkerställa och dokumentera vem som står bakom en webbplats och dess information
#### Så här kan deltagare bli mentorer
- Skugga en deltagare eller en mindre erfaren workshop-ledare och låt denne få öva på att leda aktiviteten.
- Om några deltagare är extra snabba eller säkra på uppgiften, be dem att fungera som kamrat-mentorer åt en annan grupp.
- Avsluta genom att uppmuntra deltagarna att genomföra aktiviteten med familj och vänner.
#### Se remixar från communityt

Se hur utbildare och aktivister har anpassat aktiviteten för sina specifika målgrupper i vårt [diskussionsforum](http://discourse.webmaker.org/t/testing-1-reading-for-the-web/1149/22).

**Comment by soapdog** [comment]
Hi There! Thanks a lot for this localization :smile_cat: 

Your awesome work is available at http://mozilla.github.io/mozilla-club-activity-kraken-the-code/#sv

Can you please translate the words "Search" and "Credibility" used in the buttons in the sidebar for us? thanks again!

**Comment by bobbisan** [comment]
:)

Search = Sökning
Credibility = Trovärdighet
