### ISSUE TITLE
Localization of activity.md into Swedish

### ISSUE THREAD

**Issue by bobbisan** [mozilla/mozilla-club-activity-kraken-the-code#22]
---

title: Kraken the Code
github: mozilla/mozilla-club-activity-kraken-the-code
github_label: View on Github
discourse_label: Discussion
image: square-kraken.png
competencies_label: Web Literacy Competencies
competencies:
    - {label: "Search", type: "search"}
### Kraken the Code

Skapad av [MOUSE](http://mouse.org/) och remixad för Clubs av [Mozilla](https://webmaker.org/mentor).

Deltagarna ska använda internet för att lösa mysteriet med Kraken, ett legendariskt sjöodjur, samtidigt som de **lär sig om söktermer, nyckelord (keywords), och att avgöra trovärdigheten och relevansen hos källor på nätet.**

45 minuter till en timme
### Förberelser

**Genomför den** [förberedande enkäten](http://goo.gl/forms/Uua6yKIy5E).

**Gör sedan aktiviteten själv** för att bekanta dig med den.

**Skriv ut** [Legit-O-Meter Worksheets](https://docs.google.com/a/zythepsary.com/file/d/0B1vyNnSVEMIDbDVLX1E4ZXRmclE/edit).

**Skriv rubrikerna** _”Verklig,” ”Påhittad” och ”Något mittemellan,”_ på tre papper och sätt upp dem på olika ställen i rummet.

---

10<br>min
### Introduktion

För en **kort diskussion med deltagarna om källor på nätet.**

> - Är allt du ser och läser på nätet sant?
> - Hur vet du när du kan lita på informationen på nätet?
> - Hur kan du avgöra när informationen inte är pålitlig?

**Gå sedan igenom [Legit-O-Meter Worksheets](https://docs.google.com/a/zythepsary.com/file/d/0B1vyNnSVEMIDbDVLX1E4ZXRmclE/edit)** och diskutera några tumregler för att avgöra hur pass trovärdig en webbplats är.

---

25<br>min
### Kraken the Code: Leta

Dela upp deltagarna i **grupper om 2 till 3** och förklara att varje grupp har till uppgift att **bevisa ifall det legendariska sjöodjuret, Kraken, är verkligt eller en myt.**

Grupperna börjar med att **researcha i 20 minuter.** Utifrån riktlinjerna i [Tip Sheet](legit-o-meter.html), ska grupperna **utvärdera 2 källor på internet**, dokumentera sina upptäckter på Legit-o-Metern (antingen genom att [skriva på arbetsbladet](https://docs.google.com/a/zythepsary.com/file/d/0B1vyNnSVEMIDbDVLX1E4ZXRmclE/edit) eller genom att skriva i [online-mallen](https://laura.makes.org/thimble/Mjg1NjA2NDAw/kraken-the-code-legit-o-meter)).

![Image](http://mozilla.github.io/webmaker-curriculum/images/kraken-in-progress.jpg)

**Du kan guida dem i deras process** genom dessa uppmaningar:

> - Be eleverna att prata igenom hur de går tillväga för att söka efter trovärdig information.
> - Gör en provsökning tillsammans och fråga gruppen vad som är nästa steg.
> - Para ihop elever och be dem göra en screencast där de beskriver sitt tillvägagångssätt.

![Mouse](http://mozilla.github.io/webmaker-curriculum/images/kraken-finished-example.jpg)

---

10<br>min
### Kraken the Code: Försvara

När research-fasen är slut ska **grupperna ställa sig under en av skyltarna:** ”Verklig,” ”Påhittad,” eller ”Något mittemellan”.

Fråga varje grupp vad de lärde sig om Kraken och be dem **försvara sin åsikt** med hjälp av de Legit-o-Meter worksheets de fyllt i. Deltagarna **kan byta plats** om de blir övertygade av något annat argument.

Avsluta genom att be gruppen att reflektera över sina upptäckter.

Genomför sedan den **[avslutande enkäten](http://goo.gl/forms/ezm6IXWhhM)**.

**Comment by soapdog** [comment]
Hi There! Thanks a lot for this localization :smile_cat: 

Your awesome work is available at http://mozilla.github.io/mozilla-club-activity-kraken-the-code/#sv

Can you please translate the words "Search" and "Credibility" used in the buttons in the sidebar for us? thanks again!

**Comment by bobbisan** [comment]
Great :)

Search = Sökning
Credibility = Trovärdighet

A question: Is it possible to also translate the worksheets to the activity?
