### ISSUE TITLE
Localization of aside.md into Marathi Language

### ISSUE THREAD

**Issue by chandrakantd** [mozilla/mozilla-club-activity-kraken-the-code#23]
<!DOCTYPE html>
<html lang="en" class=" is-copy-enabled">
  <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# object: http://ogp.me/ns/object# article: http://ogp.me/ns/article# profile: http://ogp.me/ns/profile#">
    <meta charset='utf-8'>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Language" content="en">
    <meta name="viewport" content="width=1020">

```
<title>mozilla-club-activity-kraken-the-code/aside.md at gh-pages · mozilla/mozilla-club-activity-kraken-the-code · GitHub</title>
<link rel="search" type="application/opensearchdescription+xml" href="/opensearch.xml" title="GitHub">
<link rel="fluid-icon" href="https://github.com/fluidicon.png" title="GitHub">
<link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-114.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-144.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144.png">
<meta property="fb:app_id" content="1401488693436528">

  <meta content="@github" name="twitter:site" /><meta content="summary" name="twitter:card" /><meta content="mozilla/mozilla-club-activity-kraken-the-code" name="twitter:title" /><meta content="mozilla-club-activity-kraken-the-code - A Mozilla Club activity called Kraken The Code" name="twitter:description" /><meta content="https://avatars2.githubusercontent.com/u/131524?v=3&amp;s=400" name="twitter:image:src" />
  <meta content="GitHub" property="og:site_name" /><meta content="object" property="og:type" /><meta content="https://avatars2.githubusercontent.com/u/131524?v=3&amp;s=400" property="og:image" /><meta content="mozilla/mozilla-club-activity-kraken-the-code" property="og:title" /><meta content="https://github.com/mozilla/mozilla-club-activity-kraken-the-code" property="og:url" /><meta content="mozilla-club-activity-kraken-the-code - A Mozilla Club activity called Kraken The Code" property="og:description" />
  <meta name="browser-stats-url" content="https://api.github.com/_private/browser/stats">
<meta name="browser-errors-url" content="https://api.github.com/_private/browser/errors">
<link rel="assets" href="https://assets-cdn.github.com/">

<meta name="pjax-timeout" content="1000">


<meta name="msapplication-TileImage" content="/windows-tile.png">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="selected-link" value="repo_source" data-pjax-transient>

<meta name="google-site-verification" content="KT5gs8h0wvaagLKAVWq8bbeNwnZZK1r1XQysX3xurLU">
<meta name="google-analytics" content="UA-3769691-2">
```

<meta content="collector.githubapp.com" name="octolytics-host" /><meta content="github" name="octolytics-app-id" /><meta content="6ADD81F7:2F42:1CE0E590:56797B3F" name="octolytics-dimension-request_id" />
<meta content="/&lt;user-name&gt;/&lt;repo-name&gt;/blob/show" data-pjax-transient="true" name="analytics-location" />
<meta content="Rails, view, blob#show" data-pjax-transient="true" name="analytics-event" />

  <meta class="js-ga-set" name="dimension1" content="Logged Out">

```
    <meta name="hostname" content="github.com">
<meta name="user-login" content="">

    <meta name="expected-hostname" content="github.com">

  <link rel="mask-icon" href="https://assets-cdn.github.com/pinned-octocat.svg" color="#4078c0">
  <link rel="icon" type="image/x-icon" href="https://assets-cdn.github.com/favicon.ico">

<meta content="2cf43ee6950340eece04f251280ca972edc11c2f" name="form-nonce" />

<link crossorigin="anonymous" href="https://assets-cdn.github.com/assets/github-2037283749006a7ebc37dc5a63a365e8cde9e5d0099e83d4a77bba85b03a6623.css" integrity="sha256-IDcoN0kAan68N9xaY6Nl6M3p5dAJnoPUp3u6hbA6ZiM=" media="all" rel="stylesheet" />
<link crossorigin="anonymous" href="https://assets-cdn.github.com/assets/github2-87b394aa7bb776e9e05abfb54eaa1193404e767a3720d64ff2c8f64c7cfb432b.css" integrity="sha256-h7OUqnu3dungWr+1TqoRk0BOdno3INZP8sj2THz7Qys=" media="all" rel="stylesheet" />




<meta http-equiv="x-pjax-version" content="696c3d92b2b36833513e39f2a164890b">
```

  <meta name="description" content="mozilla-club-activity-kraken-the-code - A Mozilla Club activity called Kraken The Code">
  <meta name="go-import" content="github.com/mozilla/mozilla-club-activity-kraken-the-code git https://github.com/mozilla/mozilla-club-activity-kraken-the-code.git">

  <meta content="131524" name="octolytics-dimension-user_id" /><meta content="mozilla" name="octolytics-dimension-user_login" /><meta content="44542610" name="octolytics-dimension-repository_id" /><meta content="mozilla/mozilla-club-activity-kraken-the-code" name="octolytics-dimension-repository_nwo" /><meta content="true" name="octolytics-dimension-repository_public" /><meta content="false" name="octolytics-dimension-repository_is_fork" /><meta content="44542610" name="octolytics-dimension-repository_network_root_id" /><meta content="mozilla/mozilla-club-activity-kraken-the-code" name="octolytics-dimension-repository_network_root_nwo" />
  <link href="https://github.com/mozilla/mozilla-club-activity-kraken-the-code/commits/gh-pages.atom" rel="alternate" title="Recent Commits to mozilla-club-activity-kraken-the-code:gh-pages" type="application/atom+xml">

  </head>

  <body class="logged_out   env-production linux vis-public page-blob">
    <a href="#start-of-content" tabindex="1" class="accessibility-aid js-skip-to-content">Skip to content</a>

```
  <div class="header header-logged-out" role="banner">
```

  <div class="container clearfix">

```
<a class="header-logo-wordmark" href="https://github.com/" data-ga-click="(Logged out) Header, go to homepage, icon:logo-wordmark">
  <span class="mega-octicon octicon-logo-github"></span>
</a>

<div class="header-actions" role="navigation">
    <a class="btn btn-primary" href="/join" data-ga-click="(Logged out) Header, clicked Sign up, text:sign-up">Sign up</a>
  <a class="btn" href="/login?return_to=%2Fmozilla%2Fmozilla-club-activity-kraken-the-code%2Fblob%2Fgh-pages%2Factivity-data%2Fcontent%2Fen%2Faside.md" data-ga-click="(Logged out) Header, clicked Sign in, text:sign-in">Sign in</a>
</div>

<div class="site-search repo-scope js-site-search" role="search">
  <!-- </textarea> --><!-- '"` --><form accept-charset="UTF-8" action="/mozilla/mozilla-club-activity-kraken-the-code/search" class="js-site-search-form" data-global-search-url="/search" data-repo-search-url="/mozilla/mozilla-club-activity-kraken-the-code/search" method="get"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" /></div>
```

  <label class="js-chromeless-input-container form-control">
    <div class="scope-badge">This repository</div>
    <input type="text"
      class="js-site-search-focus js-site-search-field is-clearable chromeless-input"
      data-hotkey="s"
      name="q"
      placeholder="Search"
      aria-label="Search this repository"
      data-global-scope-placeholder="Search GitHub"
      data-repo-scope-placeholder="Search"
      tabindex="1"
      autocapitalize="off">
  </label>
</form>
    </div>

```
  <ul class="header-nav left" role="navigation">
      <li class="header-nav-item">
        <a class="header-nav-link" href="/explore" data-ga-click="(Logged out) Header, go to explore, text:explore">Explore</a>
      </li>
      <li class="header-nav-item">
        <a class="header-nav-link" href="/features" data-ga-click="(Logged out) Header, go to features, text:features">Features</a>
      </li>
      <li class="header-nav-item">
        <a class="header-nav-link" href="https://enterprise.github.com/" data-ga-click="(Logged out) Header, go to enterprise, text:enterprise">Enterprise</a>
      </li>
      <li class="header-nav-item">
        <a class="header-nav-link" href="/pricing" data-ga-click="(Logged out) Header, go to pricing, text:pricing">Pricing</a>
      </li>
  </ul>
```

  </div>
</div>

```
<div id="start-of-content" class="accessibility-aid"></div>

  <div id="js-flash-container">
```

</div>

```
<div role="main" class="main-content">
    <div itemscope itemtype="http://schema.org/WebPage">
<div id="js-repo-pjax-container" class="context-loader-container js-repo-nav-next" data-pjax-container>
```

<div class="pagehead repohead instapaper_ignore readability-menu experiment-repo-nav">
  <div class="container repohead-details-container">

    

<ul class="pagehead-actions">

  <li>
      <a href="/login?return_to=%2Fmozilla%2Fmozilla-club-activity-kraken-the-code"
    class="btn btn-sm btn-with-count tooltipped tooltipped-n"
    aria-label="You must be signed in to watch a repository" rel="nofollow">
    <span class="octicon octicon-eye"></span>
    Watch
  </a>
  <a class="social-count" href="/mozilla/mozilla-club-activity-kraken-the-code/watchers">
    16
  </a>

  </li>

  <li>
      <a href="/login?return_to=%2Fmozilla%2Fmozilla-club-activity-kraken-the-code"
    class="btn btn-sm btn-with-count tooltipped tooltipped-n"
    aria-label="You must be signed in to star a repository" rel="nofollow">
    <span class="octicon octicon-star "></span>
    Star
  </a>

    <a class="social-count js-social-count" href="/mozilla/mozilla-club-activity-kraken-the-code/stargazers">
      3
    </a>

  </li>

  <li>
      <a href="/login?return_to=%2Fmozilla%2Fmozilla-club-activity-kraken-the-code"
        class="btn btn-sm btn-with-count tooltipped tooltipped-n"
        aria-label="You must be signed in to fork a repository" rel="nofollow">
        <span class="octicon octicon-repo-forked "></span>
        Fork
      </a>

    <a href="/mozilla/mozilla-club-activity-kraken-the-code/network" class="social-count">
      10
    </a>
  </li>
</ul>

    <h1 itemscope itemtype="http://data-vocabulary.org/Breadcrumb" class="entry-title public ">
  <span class="octicon octicon-repo "></span>
  <span class="author"><a href="/mozilla" class="url fn" itemprop="url" rel="author"><span itemprop="title">mozilla</span></a></span><span class="path-divider">/</span><strong><a href="/mozilla/mozilla-club-activity-kraken-the-code" data-pjax="#js-repo-pjax-container">mozilla-club-activity-kraken-the-code</a></strong>

  <span class="page-context-loader">
    <img alt="" height="16" src="https://assets-cdn.github.com/images/spinners/octocat-spinner-32.gif" width="16" />
  </span>

</h1>

  </div>
  <div class="container">
    
<nav class="reponav js-repo-nav js-sidenav-container-pjax js-octicon-loaders"
     role="navigation"
     data-pjax="#js-repo-pjax-container">

  <a href="/mozilla/mozilla-club-activity-kraken-the-code" aria-label="Code" aria-selected="true" class="js-selected-navigation-item selected reponav-item" data-hotkey="g c" data-selected-links="repo_source repo_downloads repo_commits repo_releases repo_tags repo_branches /mozilla/mozilla-club-activity-kraken-the-code">
    <span class="octicon octicon-code "></span>
    Code
</a>
    <a href="/mozilla/mozilla-club-activity-kraken-the-code/issues" class="js-selected-navigation-item reponav-item" data-hotkey="g i" data-selected-links="repo_issues repo_labels repo_milestones /mozilla/mozilla-club-activity-kraken-the-code/issues">
      <span class="octicon octicon-issue-opened "></span>
      Issues
      <span class="counter">19</span>
</a>
  <a href="/mozilla/mozilla-club-activity-kraken-the-code/pulls" class="js-selected-navigation-item reponav-item" data-hotkey="g p" data-selected-links="repo_pulls /mozilla/mozilla-club-activity-kraken-the-code/pulls">
    <span class="octicon octicon-git-pull-request "></span>
    Pull requests
    <span class="counter">0</span>
</a>

  <a href="/mozilla/mozilla-club-activity-kraken-the-code/pulse" class="js-selected-navigation-item reponav-item" data-selected-links="pulse /mozilla/mozilla-club-activity-kraken-the-code/pulse">
    <span class="octicon octicon-pulse "></span>
    Pulse
</a>
  <a href="/mozilla/mozilla-club-activity-kraken-the-code/graphs" class="js-selected-navigation-item reponav-item" data-selected-links="repo_graphs repo_contributors /mozilla/mozilla-club-activity-kraken-the-code/graphs">
    <span class="octicon octicon-graph "></span>
    Graphs
</a>

</nav>

  </div>
</div>

<div class="container new-discussion-timeline experiment-repo-nav">
  <div class="repository-content">

    

<a href="/mozilla/mozilla-club-activity-kraken-the-code/blob/7439e38cbe44db417f0eeef1ab4c96ceb653e4dd/activity-data/content/en/aside.md" class="hidden js-permalink-shortcut" data-hotkey="y">Permalink</a>

<div class="file-navigation js-zeroclipboard-container">
  
<div class="select-menu js-menu-container js-select-menu left">
  <button class="btn btn-sm select-menu-button js-menu-target css-truncate" data-hotkey="w"
    title="gh-pages"
    type="button" aria-label="Switch branches or tags" tabindex="0" aria-haspopup="true">
    <i>Branch:</i>
    <span class="js-select-button css-truncate-target">gh-pages</span>
  </button>

  <div class="select-menu-modal-holder js-menu-content js-navigation-container" data-pjax aria-hidden="true">

    <div class="select-menu-modal">
      <div class="select-menu-header">
        <span aria-label="Close" class="octicon octicon-x js-menu-close" role="button"></span>
        <span class="select-menu-title">Switch branches/tags</span>
      </div>

      <div class="select-menu-filters">
        <div class="select-menu-text-filter">
          <input type="text" aria-label="Filter branches/tags" id="context-commitish-filter-field" class="js-filterable-field js-navigation-enable" placeholder="Filter branches/tags">
        </div>
        <div class="select-menu-tabs">
          <ul>
            <li class="select-menu-tab">
              <a href="#" data-tab-filter="branches" data-filter-placeholder="Filter branches/tags" class="js-select-menu-tab" role="tab">Branches</a>
            </li>
            <li class="select-menu-tab">
              <a href="#" data-tab-filter="tags" data-filter-placeholder="Find a tag…" class="js-select-menu-tab" role="tab">Tags</a>
            </li>
          </ul>
        </div>
      </div>

      <div class="select-menu-list select-menu-tab-bucket js-select-menu-tab-bucket" data-tab-filter="branches" role="menu">

        <div data-filterable-for="context-commitish-filter-field" data-filterable-type="substring">

            <a class="select-menu-item js-navigation-item js-navigation-open selected"
               href="/mozilla/mozilla-club-activity-kraken-the-code/blob/gh-pages/activity-data/content/en/aside.md"
               data-name="gh-pages"
               data-skip-pjax="true"
               rel="nofollow">
              <span class="select-menu-item-icon octicon octicon-check"></span>
              <span class="select-menu-item-text css-truncate-target" title="gh-pages">
                gh-pages
              </span>
            </a>
        </div>

          <div class="select-menu-no-results">Nothing to show</div>
      </div>

      <div class="select-menu-list select-menu-tab-bucket js-select-menu-tab-bucket" data-tab-filter="tags">
        <div data-filterable-for="context-commitish-filter-field" data-filterable-type="substring">

        </div>

        <div class="select-menu-no-results">Nothing to show</div>
      </div>

    </div>
  </div>
</div>

  <div class="btn-group right">
    <a href="/mozilla/mozilla-club-activity-kraken-the-code/find/gh-pages"
          class="js-show-file-finder btn btn-sm"
          data-pjax
          data-hotkey="t">
      Find file
    </a>
    <button aria-label="Copy file path to clipboard" class="js-zeroclipboard btn btn-sm zeroclipboard-button tooltipped tooltipped-s" data-copied-hint="Copied!" type="button">Copy path</button>
  </div>
  <div class="breadcrumb js-zeroclipboard-target">
    <span class="repo-root js-repo-root"><span itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb"><a href="/mozilla/mozilla-club-activity-kraken-the-code" class="" data-branch="gh-pages" data-pjax="true" itemscope="url"><span itemprop="title">mozilla-club-activity-kraken-the-code</span></a></span></span><span class="separator">/</span><span itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb"><a href="/mozilla/mozilla-club-activity-kraken-the-code/tree/gh-pages/activity-data" class="" data-branch="gh-pages" data-pjax="true" itemscope="url"><span itemprop="title">activity-data</span></a></span><span class="separator">/</span><span itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb"><a href="/mozilla/mozilla-club-activity-kraken-the-code/tree/gh-pages/activity-data/content" class="" data-branch="gh-pages" data-pjax="true" itemscope="url"><span itemprop="title">content</span></a></span><span class="separator">/</span><span itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb"><a href="/mozilla/mozilla-club-activity-kraken-the-code/tree/gh-pages/activity-data/content/en" class="" data-branch="gh-pages" data-pjax="true" itemscope="url"><span itemprop="title">en</span></a></span><span class="separator">/</span><strong class="final-path">aside.md</strong>
  </div>
</div>

  <div class="commit-tease">
      <span class="right">
        <a class="commit-tease-sha" href="/mozilla/mozilla-club-activity-kraken-the-code/commit/4d01111c3fd9454188c050f01bd247146a3cc18f" data-pjax>
          4d01111
        </a>
        <time datetime="2015-10-19T15:04:13Z" is="relative-time">Oct 19, 2015</time>
      </span>
      <div>
        <img alt="@soapdog" class="avatar" height="20" src="https://avatars1.githubusercontent.com/u/23247?v=3&amp;s=40" width="20" />
        <a href="/soapdog" class="user-mention" rel="contributor">soapdog</a>
          <a href="/mozilla/mozilla-club-activity-kraken-the-code/commit/4d01111c3fd9454188c050f01bd247146a3cc18f" class="message" data-pjax="true" title="initial work and English locale ready. Portuguese locale is wrong and needs fixing">initial work and English locale ready. Portuguese locale is wrong and…</a>
      </div>

```
<div class="commit-tease-contributors">
  <a class="muted-link contributors-toggle" href="#blob_contributors_box" rel="facebox">
    <strong>1</strong>
     contributor
  </a>

</div>

<div id="blob_contributors_box" style="display:none">
  <h2 class="facebox-header" data-facebox-id="facebox-header">Users who have contributed to this file</h2>
  <ul class="facebox-user-list" data-facebox-id="facebox-description">
      <li class="facebox-user-list-item">
        <img alt="@soapdog" height="24" src="https://avatars3.githubusercontent.com/u/23247?v=3&amp;s=48" width="24" />
        <a href="/soapdog">soapdog</a>
      </li>
  </ul>
</div>
```

  </div>

<div class="file">
  <div class="file-header">
  <div class="file-actions">

    <div class="btn-group">
      <a href="/mozilla/mozilla-club-activity-kraken-the-code/raw/gh-pages/activity-data/content/en/aside.md" class="btn btn-sm " id="raw-url">Raw</a>
        <a href="/mozilla/mozilla-club-activity-kraken-the-code/blame/gh-pages/activity-data/content/en/aside.md" class="btn btn-sm js-update-url-with-hash">Blame</a>
      <a href="/mozilla/mozilla-club-activity-kraken-the-code/commits/gh-pages/activity-data/content/en/aside.md" class="btn btn-sm " rel="nofollow">History</a>
    </div>

        <button type="button" class="octicon-btn disabled tooltipped tooltipped-nw"
          aria-label="You must be signed in to make or propose changes">
          <span class="octicon octicon-pencil "></span>
        </button>
        <button type="button" class="octicon-btn octicon-btn-danger disabled tooltipped tooltipped-nw"
          aria-label="You must be signed in to make or propose changes">
          <span class="octicon octicon-trashcan "></span>
        </button>
  </div>

  <div class="file-info">
      <span class="file-mode" title="File mode">executable file</span>
      <span class="file-info-divider"></span>
      30 lines (20 sloc)
      <span class="file-info-divider"></span>
    1.12 KB
  </div>
</div>

  <div id="readme" class="blob instapaper_body">
    <article class="markdown-body entry-content" itemprop="mainContentOfPage"><h4><a id="user-content-audience" class="anchor" href="#audience" aria-hidden="true"><span class="octicon octicon-link"></span></a>या प्रशिक्षणास कोणते विद्यार्थी चालतील</h4>

<ul>
<li>८ वर्षांच्या पुढील वयोगटातील</li>
<li>विचारांची गंभीर पणे सुरुवात केलेले</li>
<li>MLN- मोझीला लर्निंग नेटवर्क चे सर्व सदस्य</li>
</ul>

<h4><a id="user-content-materials" class="anchor" href="#materials" aria-hidden="true"><span class="octicon octicon-link"></span></a>साहित्य</h4>

<ul>
<li>कोरे कागद व पेन</li>
<li>वेब ब्राउझर</li>
<li><a href="https://docs.google.com/a/zythepsary.com/file/d/0B1vyNnSVEMIDbDVLX1E4ZXRmclE/edit">Legit-o-Meter worksheet</a> च्या घेतलेल्या प्रिंट्स</li>
</ul>

<h4><a id="user-content-learning-objectives" class="anchor" href="#learning-objectives" aria-hidden="true"><span class="octicon octicon-link"></span></a>प्रशिक्षणाचे उद्दिष्टे</h4>

<ul>
<li>सर्च इंजीनचा वापर करून योग्य ते माहिती मिळविणे</li>
<li>वेगवेगळ्या प्रकारे सर्च करून शोधलेल्या माहितीची पडताळणी व तुलना करणे</li>
<li>विविध स्रोतांतुन मिळालेली माहिती विश्वसनीय आहे किंवा नाही याबाबतची तुलना करणे</li>
<li>काही महत्त्वाच्या टीपा वापरून शोधलेली माहिती विश्वसनीय आहे किंवा नाही हे जाणून घेणे</li>
<li>संकेतस्थळाचे मालक व त्यावरची माहिती यांची नोंद करणे</li>
</ul>

<h4><a id="user-content-how-learners-become-mentors" class="anchor" href="#how-learners-become-mentors" aria-hidden="true"><span class="octicon octicon-link"></span></a>आजचे विद्यार्थी, उद्याचे शिक्षक किंवा मार्गदर्शक कसे बनतील</h4>

<ul>
<li>उत्सुक विद्यार्थी किंवा कमी जाण असलेल्या मार्गदर्शकांना ह्या प्रशिक्षण कार्यात मदत करा.</li>
<li>काही विद्यार्थी जर लवकर शिकत असतील, तर त्यांना इतर गटांना मदत करण्यास प्रोत्साहीत करा.</li>
<li>सर्व विद्यार्थ्यांना आपल्या मित्रांना व कुटुंबीयाना शिकविण्याची विनंती करा.</li>
</ul>

<h4><a id="user-content-see-community-remixes" class="anchor" href="#see-community-remixes" aria-hidden="true"><span class="octicon octicon-link"></span></a>जागतील गटांनी केलेले कार्य</h4>

<p>वेगवेगळ्या गटांना हे प्रशिक्षण देण्यासाठी, प्रशिक्षक व कार्यकर्त्यांनी काय काय बदल केले आहेत, ते जाणून घेण्यासाठी, पुढे क्लिक करा.<a href="http://discourse.webmaker.org/t/testing-1-reading-for-the-web/1149/22">Discussion Forum</a>.</p>

</article>
  </div>

</div>

<a href="#jump-to-line" rel="facebox[.linejump]" data-hotkey="l" style="display:none">Jump to Line</a>

<div id="jump-to-line" style="display:none">
  <form accept-charset="UTF-8" action="" class="js-jump-to-line-form" method="get"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" /></div>
    <input class="linejump-input js-jump-to-line-field" type="text" placeholder="Jump to line&hellip;" aria-label="Jump to line" autofocus>
    <button type="submit" class="btn">Go</button>
</form></div>

  </div>
  <div class="modal-backdrop"></div>
</div>

```
</div>
```

  </div>

```
</div>

    <div class="container">
```

  <div class="site-footer" role="contentinfo">
    <ul class="site-footer-links right">
        <li><a href="https://status.github.com/" data-ga-click="Footer, go to status, text:status">Status</a></li>
      <li><a href="https://developer.github.com" data-ga-click="Footer, go to api, text:api">API</a></li>
      <li><a href="https://training.github.com" data-ga-click="Footer, go to training, text:training">Training</a></li>
      <li><a href="https://shop.github.com" data-ga-click="Footer, go to shop, text:shop">Shop</a></li>
        <li><a href="https://github.com/blog" data-ga-click="Footer, go to blog, text:blog">Blog</a></li>
        <li><a href="https://github.com/about" data-ga-click="Footer, go to about, text:about">About</a></li>
        <li><a href="https://github.com/pricing" data-ga-click="Footer, go to pricing, text:pricing">Pricing</a></li>

```
</ul>

<a href="https://github.com" aria-label="Homepage">
  <span class="mega-octicon octicon-mark-github " title="GitHub "></span>
```

</a>
    <ul class="site-footer-links">
      <li>&copy; 2015 <span title="0.04518s from github-fe120-cp1-prd.iad.github.net">GitHub</span>, Inc.</li>
        <li><a href="https://github.com/site/terms" data-ga-click="Footer, go to terms, text:terms">Terms</a></li>
        <li><a href="https://github.com/site/privacy" data-ga-click="Footer, go to privacy, text:privacy">Privacy</a></li>
        <li><a href="https://github.com/security" data-ga-click="Footer, go to security, text:security">Security</a></li>
        <li><a href="https://github.com/contact" data-ga-click="Footer, go to contact, text:contact">Contact</a></li>
        <li><a href="https://help.github.com" data-ga-click="Footer, go to help, text:help">Help</a></li>
    </ul>
  </div>
</div>

```
<div id="ajax-error-message" class="flash flash-error">
  <span class="octicon octicon-alert"></span>
  <button type="button" class="flash-close js-flash-close js-ajax-error-dismiss" aria-label="Dismiss error">
    <span class="octicon octicon-x"></span>
  </button>
  Something went wrong with that request. Please try again.
</div>


  <script crossorigin="anonymous" integrity="sha256-7460qJ7p88i3YTMH/liaj1cFgX987ie+xRzl6WMjSr8=" src="https://assets-cdn.github.com/assets/frameworks-ef8eb4a89ee9f3c8b7613307fe589a8f5705817f7cee27bec51ce5e963234abf.js"></script>
  <script async="async" crossorigin="anonymous" integrity="sha256-S2uOfRHrt7zoUSbTtBMMgAQfKubV1u+JAajAw/fLgNI=" src="https://assets-cdn.github.com/assets/github-4b6b8e7d11ebb7bce85126d3b4130c80041f2ae6d5d6ef8901a8c0c3f7cb80d2.js"></script>



<div class="js-stale-session-flash stale-session-flash flash flash-warn flash-banner hidden">
  <span class="octicon octicon-alert"></span>
  <span class="signed-in-tab-flash">You signed in with another tab or window. <a href="">Reload</a> to refresh your session.</span>
  <span class="signed-out-tab-flash">You signed out in another tab or window. <a href="">Reload</a> to refresh your session.</span>
</div>
```

  </body>
</html>

**Comment by soapdog** [comment]
Hi, 

Thanks a lot for your contribution.

Unfortunately we can`t use it as it is because it is not in the correct format for our use. What we need is the translation of the following files: 

[activity.md](../raw/gh-pages/activity-data/content/en/activity.md)
[aside.md](../raw/gh-pages/activity-data/content/en/aside.md)

There is a handy guide explaining the process of translation at:

https://ariefbayu.xyz/step-by-step-how-to-help-localize-web-literacy-curriculum-c6b3547838a0#.opu7147gd

Thanks again for your help and effort in moving our content into Marathi! 

I am looking forward to working with you. Please don't hesitate to respond here or ask any question you may want.

Cheers
