### ISSUE TITLE
translation of aside.md in hindi(hi_IN)

### ISSUE THREAD

**Issue by ravi103151** [mozilla/mozilla-club-activity-kraken-the-code#25]
#### दर्शक
- 8+
- महत्वपूर्ण विचारकों से शुरुआत
- एमएलएन में हर कोई
#### सामग्री
- कागज और कलम
- वेब ब्राउज़र
- मुद्रित [वैध-ओ-मापक कार्य-पत्र](https://docs.google.com/a/zythepsary.com/file/d/0B1vyNnSVEMIDbDVLX1E4ZXRmclE/edit)
#### सीखने के उद्देश्य
- खोज इंजन का उपयोग करके प्रासंगिक जानकारी का पता लगाएँ
- कई खोजों का उपयोग करके तुलनात्मक जानकारी पाना 
- उनके विश्वसनीयता का आकलन करने के लिए बहुत सारे स्रोतों से जानकारीयों का तुलना करें
- मुख्य सूचक की पहचान करके जानकारी की विश्वसनीयता पर निर्णय लें
- एक वेबसाइट और उनके विषय वस्तु के लेखकत्व का  प्रमाण पत्र दें
#### नवसिखुआ से सलाहकार कैसे बनें
- एक छात्र या कम अनुभवी अनुदेशक को सिखाये ताकि वे इस गतिविधि का नेतृत्व करने के लिए अभ्यास कर सकें.
- अगर कुछ छात्र इस गतिविधि में तेजी से आगे बढ़ता है या अधिक आत्मविश्वासी है, एक और समूह के सलाहकार सहकर्मी के लिए कहें.
- छात्रों को इस गतिविधि को उसके दोस्तों और परिवार को सिखाने के लिए प्रोत्साहित करके समापन करें.
#### समुदाय रीमिक्स देखें

हमारे [विचार-विमर्श स्थल](http://discourse.webmaker.org/t/testing-1-reading-for-the-web/1149/22) में देखें किस तरह से शिक्षकों और सक्रिय प्रतिभागी ने उनके विशिष्ट दर्शकों के लिए इस गतिविधि को संशोधित किया है.

**Comment by soapdog** [comment]
Hey there!

We have an Hindi translation at http://mozilla.github.io/mozilla-club-activity-kraken-the-code/#hi

If you are providing a new/fixed translation can you please tell me what changed? I can't read Hindi so I need help figuring out the differences.

Thanks 
andre

**Comment by ravi103151** [comment]
Dear  Team,

Sorry for late Reply!
Please check  below attachment where I have mentioned few mistakes which is
there  in present Kraken-the-code Hindi page.

So these errors I have found and I submitted new hindi page for the same.

Thank You

Regards
Ravi Kumbhkar
Mozilla Contributor
