### ISSUE TITLE
Localization of aside.md into Chinese Simplified

### ISSUE THREAD

**Issue by nizibaba** [mozilla/mozilla-club-activity-kraken-the-code#26]
测试：如何使用Github进行翻译？
Test: How to use Github translation?

**Comment by soapdog** [comment]
Hi there!

In this URL  https://ariefbayu.xyz/step-by-step-how-to-help-localize-web-literacy-curriculum-c6b3547838a0#.opu7147gd you will find a step by step tutorial on how to translate the activities. Please tell me if you need more help beyond that. We're here to help! :smile_cat:

**Comment by nizibaba** [comment]
Hi! 
Thank you for your guidance, please take a look at it, Would it be all right?
