### ISSUE TITLE
Localization of activity.md into Chinese Simplified

### ISSUE THREAD

**Issue by nizibaba** [mozilla/mozilla-club-activity-kraken-the-code#27]
---

title: Kraken the Code
github: mozilla/mozilla-club-activity-kraken-the-code
github_label: View on Github
discourse_label: Discussion
image: square-kraken.png
competencies_label: Web Literacy Competencies
competencies:
    - {label: "Search", type: "search"}
### 深海怪兽

Made by [MOUSE](http://mouse.org/) and remixed for Clubs by [Mozilla](https://webmaker.org/mentor).

学生将利用互联网了去搜索关于传说中的海洋生物--海怪的奥秘，并解释这一现象。同时学习搜索词，关键词，以及如何评估的有效性和网络资源的相关性。**

活动时间大约45分钟
### 活动准备

**完成** [前期调查问卷](http://goo.gl/forms/Uua6yKIy5E)。

接下来 **准备你的活动** 并尽可能的熟悉他。

**打印** [Legit-O-Meter Worksheets网络资源调查表](https://docs.google.com/a/zythepsary.com/file/d/0B1vyNnSVEMIDbDVLX1E4ZXRmclE/edit).

**在活动现场**准备三张标有 _“这是真实的故事,” “这是一个传说” 和 “这个故事介于两者之间,”的图片，_ 并把他们粘贴在醒目的位置

---

10<br>分钟
### 活动介绍

 **首先和今天的活动参与人员进行一个简短的沟通，可以询问一些问题，例如**

> - 你认为，你在网络上看到这些文字活动视频的信息资料是真实可信的吗？
> - 在什么情况下你可以确认你看到的信息是值得信任的？
> - 又是在什么情况下你可以确认你看到的信息是不值得信任的？

**接下来一起分享讨论 [网络资源调查表](https://docs.google.com/a/zythepsary.com/file/d/0B1vyNnSVEMIDbDVLX1E4ZXRmclE/edit)** 讨论确定一个网站的可信度一些通用规则。

---

25<br>分钟
### 深海怪兽: 讨论进行中

按照学生的对事件的看法将他们分成 **2-3个团队** 每个组的的任务就是利用计算机去上网查询资料以证明自己的观点的正确性 **他们是真实存在的或者是仅仅是一个传说.**

每一组将有**20分钟的时间去发掘并研究** 活动组织方提供的资料 [指引案例1](http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/legit-o-meter.html), 每一小组需要评估 **多个互联网信息来源**, 并把他们的发现 (记录在[纸质表格](https://docs.google.com/a/zythepsary.com/file/d/0B1vyNnSVEMIDbDVLX1E4ZXRmclE/edit) 或者是 [在线表格中](https://laura.makes.org/thimble/Mjg1NjA2NDAw/kraken-the-code-legit-o-meter)).

![Image](http://mozilla.github.io/webmaker-curriculum/images/kraken-in-progress.jpg)

**考虑以下提示指导他们的研究：** 

> - 要求每一组的每一位成员都简述一下自己是如何获得可用的信息的过程？（关键词，搜索引擎，大型的网站...)
> - 建议小组成员一起做一个示例搜索并提出下一步做什么的建议。
> - 将参与者按照观点分队组合并要求他们制作一个视频或者PPT来支持自己的观点。

![Mouse](http://mozilla.github.io/webmaker-curriculum/images/kraken-finished-example.jpg)

---

10<br>分钟
### 深海怪兽: Defense

当活动结束讨论之后, **每个小组会把自己的讨论结果标识在之前准备好的图板上:** “真实的,” “神话传说,” 或者 “不肯定，介于两只之间”.

各小组之间交换自己的调查表并交换他们之间 **不同的看法** 他们可以使用网络资源标准调查表来支持自己的观点，**如果期间有组员改变了自己的决定** 他们可以改变自己的位置。

最后要求每一组说明自己的决定，阐明本次活动中的收获

填写 **[完成后活动问卷](http://goo.gl/forms/ezm6IXWhhM)**.

**Comment by soapdog** [comment]
Yay!!!! :smile_cat: 

Thanks a lot for the awesome translation of our content into Chinese which is now online at:

http://mozilla.github.io/mozilla-club-activity-kraken-the-code/#zh-s

I've added translations for the buttons on the left sidebar for "Search" and "Credibility", can you please check if those buttons are correct?

Thanks again!
