### ISSUE TITLE
Localization of aside.md into Chinese Simplified

### ISSUE THREAD

**Issue by nizibaba** [mozilla/mozilla-club-activity-kraken-the-code#28]
#### 活动参与人员
- 8+
- 可以独立思考的受众
- 每一位都可以接受和参与的团队
#### 活动所需材料
- 纸和笔
- 网络 ，PC ，最新的浏览器
- 打印 [网络资源调查表](https://docs.google.com/a/zythepsary.com/file/d/0B1vyNnSVEMIDbDVLX1E4ZXRmclE/edit)
#### 学习目标
- 通过搜索引擎查找相关信息
- 比较并使用多个搜索对比发现信息
- 从许多来源比较信息来判断其可信度
- 通过确定关键指标决定信息的可信度
- 文档的作者及其网站内容
#### 学习者如何转变成导师
- 培养学生或不太有经验的主持人，这样他们就可以练习领导这项活动。
- 如果一些学生在活动中动作更快或更自信，请让他们与另一组同伴进行辅导。
- 活动结束之后鼓励学生教他们的朋友和家人。
#### 了解不同的社区再创作

Mozilla来自世界各地的志愿者和教育工作者根据这个题材进行了不同的再创作，您可以加入我们的讨论并和帮助我们进行更多的创作 [欢迎加入](http://discourse.webmaker.org/t/testing-1-reading-for-the-web/1149/22).

**Comment by soapdog** [comment]
Yay!!!! :smile_cat: 

Thanks a lot for the awesome translation of our content into Chinese which is now online at:

http://mozilla.github.io/mozilla-club-activity-kraken-the-code/#zh-s

I've added translations for the buttons on the left sidebar for "Search" and "Credibility", can you please check if those buttons are correct?

Thanks again!
