### ISSUE TITLE
Tranlation of aside.md to spanish

### ISSUE THREAD

**Issue by alvarmaciel** [mozilla/mozilla-club-activity-kraken-the-code#3]
#### Destinatarixs
- 8+
- Jóvenes pensadorxs críticos
- Todos en MLN
#### Materiales
- Papeles y biromes 
- Navegadores Web
- [Planilla del Legitómetro](https://ia601508.us.archive.org/30/items/LEGITOMETROES/LEGIT-O-ETER-ES.pdf)
#### Objetivos de aprendizaje
- Localizar información relevante usando motores de búsqueda.
- Comparar y contrastar la información encontrada usando múltiples búsquedas.
- Comparar la información de diversas fuentes para juzgar su veracidad.
- Decidir sobre la veracidad de la información a través de la identificación de indicadores claves.
- Documentar la autoría de una página y su contenido.
#### Como los aprendices se convierten en mentores
- Acompañar a un estudiante o facilitador menos experimentado par que pueda practicar el liderar esta actividad.
- Si un estudiante va más rápido o está más confiado con la actividad, proponerle que ayude como mentor de otro grupo de pares.
- Terminar proponiendo a sus estudiantes que enseñen usando esta actividad a sus amigos y familiares.
#### Ver remixes de la comunidad

Miren la forma en que otros educadores y activistas modificaron et actividad para sus destinatarios específicos en nuetro
 [Foro de Discusión](http://discourse.webmaker.org/t/testing-1-reading-for-the-web/1149/22).

**Comment by soapdog** [comment]
:+1: thanks a lot for the help my friend!

**Comment by soapdog** [comment]
Reopened so that people knows what is being done.
