### ISSUE TITLE
Update competencies, add 21st C skills

### ISSUE THREAD

**Issue by hannahkane** [mozilla/mozilla-club-activity-kraken-the-code#31]
As per [this doc](https://docs.google.com/document/d/15B2ccF-DSTl74SwNbyZ0W5qMu-jQNOXUS4C6BsvjF9s/edit#heading=h.hwiildxvzsx4), the competencies should be Search, Synthesize, and Evaluate, and the 21st Century Skills should be added (Problem-solving)

Also, the word "competencies" should be replaced with "skills"

**Comment by soapdog** [comment]
Done! :smile_cat: The new section was added and a new set of key/value pairs to account for the new data was added to `activity.md`
