### ISSUE TITLE
Tranlation fo activity.md to SPANISH

### ISSUE THREAD

**Issue by alvarmaciel** [mozilla/mozilla-club-activity-kraken-the-code#6]
---

title: El Código Kraken
github: mozilla/mozilla-club-activity-kraken-the-code
github_label: View on Github
discourse_label: Discussion
image: square-kraken.png
competencies_label: Web Literacy Competencies
competencies:
    - {label: "Search", type: "search"}
### El código Kraken

Hecho por [MOUSE](http://mouse.org/) y remixado por los Mozilla Clubs [Mozilla](https://webmaker.org/mentor).

Los estudiantes usarán Internet para resolver el misterio del Kraken, una legendaria criatura marina, además **aprenderemos sobre: términos de búsqueda, palabras claves, y cómo evaluar la validez y relevancia de las funetes web.**

45 minutos a una hora
### Preparación

~~**Completar el** [cuestionario pre-actividad](http://goo.gl/forms/Uua6yKIy5E).~~

Después: **hacer la actividad por su cuenta** para familiarizarce con ella.

**Imprimir** la [planilla del LEGITOMETRO](https://ia601508.us.archive.org/30/items/LEGITOMETROES/LEGIT-O-ETER-ES.pdf).

**Escribir en tres papeles**: _“Real,” “Imaginario” y “Algo en el medio”_ y cuelgarlas en diferentes partes del aula o espacio de trabajo.

---

10<br>min
### Introducción

Inicien una breve charla con sus estudiantes sobre los contenidos web.

> - ¿Todo lo que ven o leen en la web es verdad?
> - ¿Cómo saben cuándo la información en internet es confiable?
> - ¿Cómo es que se dan cuenta de que la información no es confiable?

---

25<br>min
### El código Kraken: Búsqueda

Organicen a lxs estudiantes en **grupos de a 2 o 3 participantes** y comenten que el desafío de cada grupo es **comprobar si el legendario moustro, el kraken, es real o sólo un mito**.

Los grupos **empezarán usando 20 minutos para buscar información en la web** usando la [guía de tips de la planitilla](https://ia601508.us.archive.org/30/items/LEGITOMETROES/LEGIT-O-ETER-ES.pdf), deberan evaluar 2 fuentes de internet, documentar lo que encuentran en LEGITOMETROr (ya sea [escribiendo en la hoja impresa](https://ia601508.us.archive.org/30/items/LEGITOMETROES/LEGIT-O-ETER-ES.pdf) o editando la [plantilla online](https://d157rqmxrxj6ey.cloudfront.net/amaciel/10587/)). 

![Image](http://mozilla.github.io/webmaker-curriculum/images/kraken-in-progress.jpg)

**Consideren guiar las búsquedas con los siguientes indicaciones::

> - Tengan charlas individuales con los participantes sobre los procesos en búsquedas de información.
> - Hagan una búsqueda de ejemplo juntos y pregunten al grupo como seguir bucando.
> - Junten a los alumnos y solicitenles que creen un screencast explicando sus decisicones en las búsquedas.

![Mouse](http://mozilla.github.io/webmaker-curriculum/images/kraken-finished-example.jpg)

---

10<br>min
### El código Kraken: Defensa

Al final del período de búsqueda, **los grupos se tendrán que ubicar debajo de uno de los carteles**: “Real,” “Imaginario,” or “Algo en el medio”.

Cada grupo comentará que es lo que encontraron sobre el Kraken, soliciten que **defiendan sus opiniones usando la plantilla Legit-o-Meter que llenaron**. Los participantes pueden cambiar de lugar si escuchan argumentos convincentes.

Terminen solicitando al grupo que elaboren una reflexion de lo que encontraron.

Completen el **[cuestionario post-actividad](http://goo.gl/forms/JBw5uvEbE1)**.

**Comment by soapdog** [comment]
:+1: thanks a lot for the help my friend!

**Comment by soapdog** [comment]
Reopened so that people knows what is being done.
