### ISSUE TITLE
Translation for activity.md into Bengali

### ISSUE THREAD

**Issue by bellayet** [mozilla/mozilla-club-activity-kraken-the-code#7]
---

title: Kraken the Code
github: mozilla/mozilla-club-activity-kraken-the-code
github_label: View on Github
discourse_label: Discussion
image: square-kraken.png
competencies_label: Web Literacy Competencies
competencies:
    - {label: "Search", type: "search"}
### কোড ক্রাকেন

তৈরি করেছে [MOUSE](http://mouse.org/) and ক্লাবের জন্য রিমিক্স করেছে [মজিলা](https://webmaker.org/mentor).

শিক্ষার্থীরা ইন্টারনেটের সাহায্যে ক্রাকেনের রহস্য উন্মোচন করবে, একটি পৌরণিক সামুদ্রিক জীব, এর সাথে সাথে **সার্চ টার্ম, কীওয়ার্ড সম্পর্কে শিখতে পারবে, এবং কিভাবে ওয়েব সোর্সের বৈধতা এবং প্রাসঙ্গিকতা যাচাই করতে হয় তা জানবে।**

৪৫ মিনিট থেকে ৬০ মিনিটি
### প্রস্তুতি

**সম্পূর্ণ করুন** [প্রাক-কার্যকলাপ প্রশ্নোত্তর](http://goo.gl/forms/Uua6yKIy5E).

পরে কার্যকলাপের সাথে পরিচিত হতে **এর কার্যকলাপ নিজে করুন**।

**প্রিন্ট করে নিন** [Legit-O-Meter ওয়ার্কশীট](https://docs.google.com/a/zythepsary.com/file/d/0B1vyNnSVEMIDbDVLX1E4ZXRmclE/edit).

**তিন টুকতো কাগজে লিখুন** _“বাস্তবিক,” “কাল্পনিক” ও “এর মাঝামাঝি কিছু,”_ এবং ঘরের বিভিন্ন পাশে এগুলো ঝুলিয়ে দিন।

---

১০<br>মিনিটি
### পরিচিতি

**শিক্ষার্থীদের সাথে ওয়েব সোর্স সম্পর্কে বিস্তারিত আলোচনা করুন।**

> - অনলাইনে আমরা যা দেখি বা পড়ি তার সবকিছুই কি সত্যি?
> - কখন আপনি জানবেন যে ইন্টারনেটে দেওয়া তথ্যটি নির্ভরযোগ্য?
> - কখন আপনি বলতে পারবেন তথ্যটি নির্ভরযোগ্য নয়?

**তারপর কোন ওয়েবসাইটের বিশ্বাসযোগ্যতা কিভাবে নির্ণয় করা যায় তার সাধারণ কিছু নিয়ম সম্পর্কে আলোচনা করতে [Legit-O-Meter ওয়ার্কশীট](https://docs.google.com/a/zythepsary.com/file/d/0B1vyNnSVEMIDbDVLX1E4ZXRmclE/edit)** পর্যালোচনা করুন।

---

২৫<br>মিনিটি
### কোড ক্রাকেন: শীকার

শিক্ষার্থীদের **২ বা ৩ দলে ভাগ** করুন এবং বুঝিয়ে বলুন প্রতিটি গ্রুপের চ্যালেঞ্জ হল **প্রমাণ করতে হবে পৌরণিক দৈত্য, ক্রাকেন, সত্যি নাকি শ্রুতি।**

দলগুলো শুরু করবে **২০ মিনিট গবেষণায় ব্যয় করবে।** [পরামর্শ শীট](legit-o-meter.html) এর নির্দেশনা ব্যবহার করে, দলগুলো **২টি ইন্টারনেট সোর্স পর্যালোচনা করবে**, তারা যে সব তথ্য খুঁজে পেল তা Legit-o-Meter এ লিখে রাখবে (অথবা [হ্যান্ডাউটে লিখবে](https://docs.google.com/a/zythepsary.com/file/d/0B1vyNnSVEMIDbDVLX1E4ZXRmclE/edit) অথবা [অনলাইন টেম্পলেট](https://laura.makes.org/thimble/Mjg1NjA2NDAw/kraken-the-code-legit-o-meter) সম্পাদনা করবে)

![Image](http://mozilla.github.io/webmaker-curriculum/images/kraken-in-progress.jpg)

এই সব বিষয় উল্লেখ করে বার বার **তাদের গবেষণাকে নির্দেশনা দিন**:

> - শিক্ষার্থীকে বলুন প্রত্যেকে আলাদাভাবে বিশ্বাসযোগ্য তথ্য খুঁজে পাওয়ার উপায় সম্পর্কে কথা বলতে।
> - সকলে মিলে একবার উদাহরণস্বরুপ অনুসন্ধান করুন এবং দলকে জিজ্ঞেস করুন পরবর্তীতে কি করনীয়।
> - শিক্ষার্থীদের দুইজন করে জোড়া করুন এবং তাদের বলুন তাদের সিদ্ধান্তকে ব্যাখ্যা করে এমন একটি স্ক্রিনকাস্ট তৈরি করতে।

![Mouse](http://mozilla.github.io/webmaker-curriculum/images/kraken-finished-example.jpg)

---

১০<br>মিনিটি
### কোড ক্রাকেন: প্রতিরক্ষা

গবেষণা শেষ হলে, **দলগুলো তাদের পছন্দনীয় চিহ্নের নিচে দাড়াবে:** “বাস্তবিক,” “কাল্পনিক,” অথবা “এর মাঝামাঝি কিছু”।

প্রত্যেক দলকে জিজ্ঞেস করুন তারা ক্রাকেন সম্পর্কে কি খুঁজে পেল এবং Legit-o-Meter ওয়ার্কশীট যা তারা পূরণ করেছে তা ব্যবহার করে **তাদের মতামতের পক্ষে** বলতে বলুন। অংশগ্রহণকারীরা **তাদের অবস্থা পরিবর্তন করতে পারবে** যদি জোরালো যুক্তি থাকে।

দলগুলোকে জিজ্ঞেস করুন তারা কি শিখলো সে সম্পর্কে বলতে এবং শেষ করুন।

**সম্পূর্ণ করুন** [কার্যকলাপ-পরবর্তী প্রশ্নোত্তর](http://goo.gl/forms/ezm6IXWhhM)**।

**Comment by soapdog** [comment]
Thanks a lot for the translation! Its now live! :smile_cat: 

Awesome work!
