### ISSUE TITLE
Translation for aside.md into Bengali

### ISSUE THREAD

**Issue by bellayet** [mozilla/mozilla-club-activity-kraken-the-code#8]
#### দর্শক
- ৮+
- সিস্টেম চিন্তাবিদের শুরু
- MLN এ সবাই
#### উপকরণ
- কলম ও কাগজ
- ওয়েব ব্রাউজার
- প্রিন্ট করা [Legit-o-Meter ওয়ার্কশীট](https://docs.google.com/a/zythepsary.com/file/d/0B1vyNnSVEMIDbDVLX1E4ZXRmclE/edit)
#### শিক্ষণের উদ্দেশ্য
- সার্চ ইঞ্জিনের সাহায্যে সম্পর্কিত তথ্য খুঁজে পাওয়া
- একাধিক সার্চে পাওয়া তথ্যগুলোর তুলনা করা এবং পার্থক্য করতে পারা
- একাধিক সোর্সের তথ্যের তুলনা করে এর বিশ্বাসযোগ্যতা নির্ণয় করতে পারা
- মূল সূচকগুলো সনাক্ত করে তথ্যের বিশ্বাসযোগ্যতার বিষয়ে সিদ্ধান্তে উপনীত হতে পারা
- কোন ওয়েবসাইট এবং তার কন্টেন্টের লিপিবদ্ধ করতে পারা
#### কিভাবে শিক্ষার্থী মেন্টরে পরিনত হতে পারে
- কোন শিক্ষার্থী বা কম ভিজ্ঞ সহায়তাকারীদের নজরে রাখুন যেন তারা নিজেরা এই কার্যকলাপে নেতৃত্ব দিয়ে অনুশীলন করতে পারে।
- যদি কোন ছাত্র দ্রুত এগিয়ে যায় বা কার্যকলাপে বেশি আত্মবিশ্বাসী হয়, তাদের বলুন অন্য দলকে মেন্টরিং করতে।
- ছাত্রদের এই বলে শেষ করুন যেন তারা এই কার্যকলাপ তাদের বন্ধ ও স্বজনদের শেখায়।
#### কমিউনিটি রিমিক্স দেখুন

[আলোচনা ফোরাম] এ দেখুন কিভাবে শিক্ষাবিদ ও কর্মীরা এই কার্যকলাপকে কোন নির্দিষ্ট দর্শকের জন্য রিমিক্স করেছে (http://discourse.webmaker.org/t/testing-1-reading-for-the-web/1149/22)।

**Comment by soapdog** [comment]
Thanks a lot for the translation! Its now live! :smile_cat: 

Awesome work!
