### ISSUE TITLE
Localization of activity.md into Indonesian

### ISSUE THREAD

**Issue by harlyumboh** [mozilla/mozilla-club-activity-kraken-the-code#9]
---

title: Kraken the Code
github: mozilla/mozilla-club-activity-kraken-the-code
github_label: View on Github
discourse_label: Discussion
image: square-kraken.png
competencies_label: Web Literacy Competencies
competencies:
    - {label: "Search", type: "search"}
### Kraken the Code

DIbuat oleh [MOUSE](http://mouse.org/) dan di remix untuk Klub berdasarkan [Mozilla](https://webmaker.org/mentor).

Peserta didik akan menggunakan Internet untuk memecahkan misteri Kraken, makhluk laut yang legendaris, selain itu juga **belajar tentang istilah pencarian, kata kunci, dan bagaimana menilai validitas dan relevansi sumber web.**

45 menit sampai 1 jam
### Persiapan

*_Lengkapi *_ [Survey Sebelum Kegiatan](http://goo.gl/forms/Uua6yKIy5E).

Berikutnya *\* melakukan aktivitas sendiri *\*  agar menjadi lebih familiar .

**Mencetak** [Lembar Kerja Legit-O-Meter](https://docs.google.com/a/zythepsary.com/file/d0B1vyNnSVEMIDbDVLX1E4ZXRmclE/edit).

**Berikan label 3 lembar kertas** dengan _“Nyata,” “Imajinasi” and “Diantaranya,”_ dan gantung pada sisi yang berbeda di ruangan.

---

10<br>Menit
### Pendahuluan

buatlah **percakapan singkat dengan peserta didik tentang sumber web.**

> - Apakah semua yang anda baca atau menonton online benar?
> - Bagaimana Anda tahu kapan informasi di internet dapat diandalkan?
> - Bagaimana Anda tahu kapan itu tidak dapat diandalkan?

**Kemudian meninjau [Lembar Kerja Legit-O-Meter](https://docs.google.com/a/zythepsary.com/file/d/0B1vyNnSVEMIDbDVLX1E4ZXRmclE/edit)** untuk membahas beberapa aturan umum dalam menentukan kredibilitas dari sebuah website.

---

25<br>menit
### Kode Kraken : Berburu

Pisahkan peserta didik dalam **2 atau 3 kelompok** dan menjelaskan bahwa tantangan masing-masing kelompok adalah untuk *\* membuktikan apakah rakasa legendaris, Kraken, adalah nyata atau mitos.**

Kelompok memulai dengan **menyelesaikan 20 menit untuk meneliti.** Menggunakan pedoman dari [Lembar tips](legit-o-meter.html), kelompok harus **mengevaluasi 2 sumber internet**, mendokumentasikan temuan mereka pada Legit-o-Meter (baik dengan [menulis di handout](https://docs.google.com/a/zythepsary.com/file/d/0B1vyNnSVEMIDbDVLX1E4ZXRmclE/edit) atau mengedit [template online](https://laura.makes.org/thimble/Mjg1NjA2NDAw/kraken-the-code-legit-o-meter)).

![Image](http://mozilla.github.io/webmaker-curriculum/images/kraken-in-progress.jpg)

**Pertimbangkan membimbing penelitian mereka** dengan petunjuk berikut:

> - Mintalah peserta didik secara individual untuk menjelaskan proses mencari informasi yang dapat diandalkan.
> - Lakukan contoh pencarian bersama-sama dan bertanya kepada kelompok apa yang harus dilakukan selanjutnya.
> - Peserta didik dibuat berpasangan dan mintalah mereka untuk membuat sebuah screencast untuk menjelaskan hasilnya.

![Mouse](http://mozilla.github.io/webmaker-curriculum/images/kraken-finished-example.jpg)

---

10<br>Menit
### Kode Kraken : Bertahan

Pada akhir periode penelitian, **kelompok akan berdiri di bawah salah satu tanda:** “Nyata,” “Imajinasi,” atau “Sesuatu diantaranya”.

Mintalah setiap kelompok apa yang mereka tahu  tentang Kraken dan **mempertahankan pendapat mereka** menggunakan lembar kerja Legit-o-Meter yang di isi. Peserta **dapat mengubah posisi** jika mereka mendengar pendapat yang meyakinkan.

Simpulkan dengan meminta kelompok untuk merefleksikan apa yang mereka temukan.

Lengkapi **[Survey Setelah Kegiatan](http://goo.gl/forms/ezm6IXWhhM)**.

**Comment by soapdog** [comment]
Awesome work, thanks a lot for your help :smile_cat: This L10N is now available at http://mozilla.github.io/mozilla-club-activity-kraken-the-code/#id

**Comment by soapdog** [comment]
Also, I was checking your profile and could not find your email. Can you please post it here or if you're privacy conscious with it, then, can you send me an email at andre@mozillafoundation.org ?

We have a surprise :-D

**Comment by harlyumboh** [comment]
thanks so much @soapdog i have send mail
